//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.05 at 11:33:26 AM KST 
//

package org.oliot.epcis.model;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * 
 * specific header(s) including the Standard Business Document Header.
 * 
 * 
 * <p>
 * Java class for EPCISHeaderType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EPCISHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}StandardBusinessDocumentHeader" minOccurs="0"/>
 *         &lt;element name="extension" type="{urn:epcglobal:epcis:xsd:2}EPCISHeaderExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EPCISHeaderType", propOrder = { "standardBusinessDocumentHeader", "extension" })
public class EPCISHeaderType {

	@XmlElement(name = "StandardBusinessDocumentHeader", namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")
	protected StandardBusinessDocumentHeader standardBusinessDocumentHeader;
	protected EPCISHeaderExtensionType extension;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	/**
	 * Gets the value of the standardBusinessDocumentHeader property.
	 * 
	 * @return possible object is {@link StandardBusinessDocumentHeader }
	 * 
	 */
	public StandardBusinessDocumentHeader getStandardBusinessDocumentHeader() {
		return standardBusinessDocumentHeader;
	}

	/**
	 * Sets the value of the standardBusinessDocumentHeader property.
	 * 
	 * @param value allowed object is {@link StandardBusinessDocumentHeader }
	 * 
	 */
	public void setStandardBusinessDocumentHeader(StandardBusinessDocumentHeader value) {
		this.standardBusinessDocumentHeader = value;
	}

	/**
	 * Gets the value of the extension property.
	 * 
	 * @return possible object is {@link EPCISHeaderExtensionType }
	 * 
	 */
	public EPCISHeaderExtensionType getExtension() {
		return extension;
	}

	/**
	 * Sets the value of the extension property.
	 * 
	 * @param value allowed object is {@link EPCISHeaderExtensionType }
	 * 
	 */
	public void setExtension(EPCISHeaderExtensionType value) {
		this.extension = value;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed property
	 * on this class.
	 * 
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 * 
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 * 
	 * 
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

}
