//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:39:48 PM KST 
//


package org.oliot.model.oliot;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;


@Entity
public class QuantityElement {
	
	
	@Id @GeneratedValue
    private int id;
    protected String epcClass;
    protected float quantity;
    protected String uom;
    
    
    
    
    
    
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getEpcClass() {
		return epcClass;
	}
	public void setEpcClass(String epcClass) {
		this.epcClass = epcClass;
	}
	public float getQuantity() {
		return quantity;
	}
	public void setQuantity(float quantity) {
		this.quantity = quantity;
	}
	public String getUom() {
		return uom;
	}
	public void setUom(String uom) {
		this.uom = uom;
	}
	public QuantityElement(int id, String epcClass, float quantity, String uom) {
		super();
		this.id = id;
		this.epcClass = epcClass;
		this.quantity = quantity;
		this.uom = uom;
	}
	public QuantityElement() {
		super();
	}
	public QuantityElement(String epcClass, float quantity, String uom) {
		super();
		this.epcClass = epcClass;
		this.quantity = quantity;
		this.uom = uom;
	}

    
    
   

}
