//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:39:48 PM KST 
//


package org.oliot.model.oliot;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Transient;



@Entity
public class TransformationEventExtension {

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
//	@OneToMany
//	List<MapExt> mapExt=new ArrayList<MapExt>();
	   
	@Transient
    protected List<String> any;
	@Transient
    private Map<String, String> otherAttributes = new HashMap<String, String>();
	
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public List<String> getAny() {
		return any;
	}
	public void setAny(List<String> any) {
		this.any = any;
	}
	public Map<String, String> getOtherAttributes() {
		return otherAttributes;
	}
	public void setOtherAttributes(Map<String, String> otherAttributes) {
		this.otherAttributes = otherAttributes;
	}
//	public List<MapExt> getMapExt() {
//		return mapExt;
//	}
//	public void setMapExt(List<MapExt> mapExt) {
//		this.mapExt = mapExt;
//	}
	
	

}
