package org.oliot.epcis.model.cbv;

public enum PreservationTechniqueCode {
	ACIDIFICATION, ALCOHOL_CURING, ATTESTED_MILK, BOILING, BRINING, CANNING, COLD_SMOKE_CURING, CONSERVE, DEHYDRATION,
	DRYING, FERMENTATION, FREEZE_DRYING, FREEZING, HIGH_TEMPERATURE_TREATED_MILK, HOT_SMOKE_CURING, IONISATION,
	IRRADIATION, PASTEURISATION, QUICK_FREEZING, SALT_CURING, SOUS_VIDE, STERILISATION, SUGAR_CURING,
	ULTRA_HIGH_TEMPERATURE, UNDER_MODIFIED_ATMOSPHERE, VACUUM_PACKED
}
