//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.10 at 02:39:29 PM KST 
//

package org.oliot.model.epcis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EPCISMasterDataType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EPCISMasterDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VocabularyList" type="{urn:epcglobal:epcis:xsd:1}VocabularyListType"/>
 *         &lt;element name="extension" type="{urn:epcglobal:epcis:xsd:1}EPCISMasterDataExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EPCISMasterDataType", propOrder = { "vocabularyList", "extension" })
public class EPCISMasterDataType {

	@XmlElement(name = "VocabularyList", required = true)
	protected VocabularyListType vocabularyList;
	protected EPCISMasterDataExtensionType extension;

	/**
	 * Gets the value of the vocabularyList property.
	 * 
	 * @return possible object is {@link VocabularyListType }
	 * 
	 */
	public VocabularyListType getVocabularyList() {
		return vocabularyList;
	}

	/**
	 * Sets the value of the vocabularyList property.
	 * 
	 * @param value
	 *            allowed object is {@link VocabularyListType }
	 * 
	 */
	public void setVocabularyList(VocabularyListType value) {
		this.vocabularyList = value;
	}

	/**
	 * Gets the value of the extension property.
	 * 
	 * @return possible object is {@link EPCISMasterDataExtensionType }
	 * 
	 */
	public EPCISMasterDataExtensionType getExtension() {
		return extension;
	}

	/**
	 * Sets the value of the extension property.
	 * 
	 * @param value
	 *            allowed object is {@link EPCISMasterDataExtensionType }
	 * 
	 */
	public void setExtension(EPCISMasterDataExtensionType value) {
		this.extension = value;
	}

}
