//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.10 at 02:39:29 PM KST 
//

package org.oliot.model.epcis;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for QuantityElementType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="QuantityElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="epcClass" type="{urn:epcglobal:epcis:xsd:1}EPCClassType"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *           &lt;element name="uom" type="{urn:epcglobal:epcis:xsd:1}UOMType" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuantityElementType", propOrder = { "epcClass", "quantity", "uom" })
public class QuantityElementType {

	@XmlElement(required = true)
	protected String epcClass;
	protected BigDecimal quantity;
	protected String uom;

	/**
	 * Gets the value of the epcClass property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpcClass() {
		return epcClass;
	}

	/**
	 * Sets the value of the epcClass property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpcClass(String value) {
		this.epcClass = value;
	}

	/**
	 * Gets the value of the quantity property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getQuantity() {
		return quantity;
	}

	/**
	 * Sets the value of the quantity property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setQuantity(BigDecimal value) {
		this.quantity = value;
	}

	/**
	 * Gets the value of the uom property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUom() {
		return uom;
	}

	/**
	 * Sets the value of the uom property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUom(String value) {
		this.uom = value;
	}

}
