//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.05 at 11:33:26 AM KST 
//

package org.oliot.epcis.model;

import javax.xml.namespace.QName;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for QuantityElementType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="QuantityElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="epcClass" type="{urn:epcglobal:epcis:xsd:2}EPCClassType"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *           &lt;element name="uom" type="{urn:epcglobal:epcis:xsd:2}UOMType" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuantityElementType", propOrder = { "epcClass", "quantity", "uom" })
public class QuantityElementType {

	@XmlElement(required = true)
	@XmlSchemaType(name = "anyURI")
	protected String epcClass;
	@XmlElementRef(name = "quantity", type = JAXBElement.class, required = false)
	protected JAXBElement<Double> quantity;
	protected String uom;

	public QuantityElementType() {
	}

	public QuantityElementType(String epcClass, Double quantity, String uom) {
		this.epcClass = epcClass;
		if (quantity != null)
			this.quantity = new JAXBElement<Double>(new QName("", "quantity"), Double.class, quantity);
		this.uom = uom;
	}

	/**
	 * Gets the value of the epcClass property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpcClass() {
		return epcClass;
	}

	/**
	 * Sets the value of the epcClass property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEpcClass(String value) {
		this.epcClass = value;
	}

	/**
	 * Gets the value of the quantity property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link Double
	 *         }{@code >}
	 * 
	 */
	public JAXBElement<Double> getQuantity() {
		return quantity;
	}

	/**
	 * Sets the value of the quantity property.
	 * 
	 * @param value allowed object is {@link JAXBElement }{@code <}{@link Double
	 *              }{@code >}
	 * 
	 */
	public void setQuantity(JAXBElement<Double> value) {
		this.quantity = value;
	}

	/**
	 * Gets the value of the uom property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUom() {
		return uom;
	}

	/**
	 * Sets the value of the uom property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setUom(String value) {
		this.uom = value;
	}

}
