//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.19 at 01:15:43 PM KST 
//


package org.oliot.epcis.model;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.*;
import org.w3c.dom.Element;


/**
 * <p>Java class for SensorElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SensorElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sensorMetadata" type="{urn:epcglobal:epcis:xsd:2}SensorMetadataType" minOccurs="0"/>
 *         &lt;element name="sensorReport" type="{urn:epcglobal:epcis:xsd:2}SensorReportType" maxOccurs="unbounded"/>
 *         &lt;element name="extension" type="{urn:epcglobal:epcis:xsd:2}SensorElementExtensionType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SensorElementType", propOrder = {
    "sensorMetadata",
    "sensorReport",
    "extension",
    "any"
})
public class SensorElementType {

    protected SensorMetadataType sensorMetadata;
    @XmlElement(required = true)
    protected List<SensorReportType> sensorReport;
    protected SensorElementExtensionType extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the sensorMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link SensorMetadataType }
     *     
     */
    public SensorMetadataType getSensorMetadata() {
        return sensorMetadata;
    }

    /**
     * Sets the value of the sensorMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link SensorMetadataType }
     *     
     */
    public void setSensorMetadata(SensorMetadataType value) {
        this.sensorMetadata = value;
    }

    /**
     * Gets the value of the sensorReport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorReport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorReport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorReportType }
     * 
     * 
     */
    public List<SensorReportType> getSensorReport() {
        if (sensorReport == null) {
            sensorReport = new ArrayList<SensorReportType>();
        }
        return this.sensorReport;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link SensorElementExtensionType }
     *     
     */
    public SensorElementExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link SensorElementExtensionType }
     *     
     */
    public void setExtension(SensorElementExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    public void setSensorReport(List<SensorReportType> sensorReport) {
        this.sensorReport = sensorReport;
    }

    public void setAny(List<Object> any) {
        this.any = any;
    }
}
