//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.05 at 11:33:26 AM KST 
//

package org.oliot.epcis.model;

import java.util.HashMap;
import java.util.Map;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for SensorMetadataType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SensorMetadataType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="time" type="{urn:epcglobal:epcis:xsd:2}DateTimeStamp" />
 *       &lt;attribute name="deviceID" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="deviceMetadata" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="rawData" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="startTime" type="{urn:epcglobal:epcis:xsd:2}DateTimeStamp" />
 *       &lt;attribute name="endTime" type="{urn:epcglobal:epcis:xsd:2}DateTimeStamp" />
 *       &lt;attribute name="bizRules" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="dataProcessingMethod" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SensorMetadataType", propOrder = { "value" })
public class SensorMetadataType {

	@XmlValue
	protected String value;
	@XmlAttribute(name = "time")
	protected XMLGregorianCalendar time;
	@XmlAttribute(name = "deviceID")
	@XmlSchemaType(name = "anyURI")
	protected String deviceID;
	@XmlAttribute(name = "deviceMetadata")
	@XmlSchemaType(name = "anyURI")
	protected String deviceMetadata;
	@XmlAttribute(name = "rawData")
	@XmlSchemaType(name = "anyURI")
	protected String rawData;
	@XmlAttribute(name = "startTime")
	protected XMLGregorianCalendar startTime;
	@XmlAttribute(name = "endTime")
	protected XMLGregorianCalendar endTime;
	@XmlAttribute(name = "bizRules")
	@XmlSchemaType(name = "anyURI")
	protected String bizRules;
	@XmlAttribute(name = "dataProcessingMethod")
	@XmlSchemaType(name = "anyURI")
	protected String dataProcessingMethod;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	public void setOtherAttributes(Map<QName, String> otherAttributes) {
		this.otherAttributes = otherAttributes;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the time property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getTime() {
		return time;
	}

	/**
	 * Sets the value of the time property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setTime(XMLGregorianCalendar value) {
		this.time = value;
	}

	/**
	 * Gets the value of the deviceID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceID() {
		return deviceID;
	}

	/**
	 * Sets the value of the deviceID property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDeviceID(String value) {
		this.deviceID = value;
	}

	/**
	 * Gets the value of the deviceMetadata property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeviceMetadata() {
		return deviceMetadata;
	}

	/**
	 * Sets the value of the deviceMetadata property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDeviceMetadata(String value) {
		this.deviceMetadata = value;
	}

	/**
	 * Gets the value of the rawData property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRawData() {
		return rawData;
	}

	/**
	 * Sets the value of the rawData property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setRawData(String value) {
		this.rawData = value;
	}

	/**
	 * Gets the value of the startTime property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getStartTime() {
		return startTime;
	}

	/**
	 * Sets the value of the startTime property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setStartTime(XMLGregorianCalendar value) {
		this.startTime = value;
	}

	/**
	 * Gets the value of the endTime property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getEndTime() {
		return endTime;
	}

	/**
	 * Sets the value of the endTime property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setEndTime(XMLGregorianCalendar value) {
		this.endTime = value;
	}

	/**
	 * Gets the value of the bizRules property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBizRules() {
		return bizRules;
	}

	/**
	 * Sets the value of the bizRules property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBizRules(String value) {
		this.bizRules = value;
	}

	/**
	 * Gets the value of the dataProcessingMethod property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDataProcessingMethod() {
		return dataProcessingMethod;
	}

	/**
	 * Sets the value of the dataProcessingMethod property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDataProcessingMethod(String value) {
		this.dataProcessingMethod = value;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed property
	 * on this class.
	 * 
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 * 
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 * 
	 * 
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

}
