//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:39:48 PM KST 
//


package org.oliot.model.oliot;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.namespace.QName;

import org.w3c.dom.Element;


@Entity
public class BusinessLocationExtension {

	
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
    private int id;

	@Transient
	private String fieldname;
	@Transient
	private String prefix;
	@Transient
	private int intValue;
	@Transient
	private float floatValue;
	@Transient
	private Date dateValue;
	@Transient
	private String stringValue;
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	

	public String getFieldname() {
		return fieldname;
	}

	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}

	public String getPrefix() {
		return prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	public int getIntValue() {
		return intValue;
	}

	public void setIntValue(int intValue) {
		this.intValue = intValue;
	}

	public float getFloatValue() {
		return floatValue;
	}

	public void setFloatValue(float floatValue) {
		this.floatValue = floatValue;
	}

	public Date getDateValue() {
		return dateValue;
	}

	public void setDateValue(Date dateValue) {
		this.dateValue = dateValue;
	}

	public String getStringValue() {
		return stringValue;
	}

	public void setStringValue(String stringValue) {
		this.stringValue = stringValue;
	}

	
	public BusinessLocationExtension() {
		super();
	}

	public BusinessLocationExtension(BusinessLocation businessLocation,
			String fieldname, String prefix, int intValue, float floatValue,
			Date dateValue, String stringValue) {
		super();
		
		this.fieldname = fieldname;
		this.prefix = prefix;
		this.intValue = intValue;
		this.floatValue = floatValue;
		this.dateValue = dateValue;
		this.stringValue = stringValue;
	}


	@Transient
    @XmlAnyElement(lax = true)
    protected List<Object> any;
	@Transient
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    public void setAny(List<Object> any) {
		this.any = any;
	}

	public void setOtherAttributes(Map<QName, String> otherAttributes) {
		this.otherAttributes = otherAttributes;
	}

	/**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

	public BusinessLocationExtension(String fieldname) {
		super();
		this.fieldname = fieldname;
	}

	public BusinessLocationExtension(String fieldname, String prefix,
			int intValue, float floatValue, String stringValue,
			List<Object> any, Map<QName, String> otherAttributes) {
		super();
		this.fieldname = fieldname;
		this.prefix = prefix;
		this.intValue = intValue;
		this.floatValue = floatValue;
		this.stringValue = stringValue;
		this.any = any;
		this.otherAttributes = otherAttributes;
	}

	public BusinessLocationExtension(BusinessLocation businessLocation,
			String fieldname, String prefix, int intValue, float floatValue,
			String stringValue) {
		super();
		
		this.fieldname = fieldname;
		this.prefix = prefix;
		this.intValue = intValue;
		this.floatValue = floatValue;
		this.stringValue = stringValue;
	}

}
