//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:39:48 PM KST 
//


package org.oliot.model.oliot;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;


@Entity
public class EPCList {

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	@OneToMany
	protected List<EPCN> epc =new ArrayList<EPCN>();

	
	
	
    public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}


	public void setEpc(List<EPCN> epc) {
		this.epc = epc;
	}

	
    public List<EPCN> getEpc() {
        if (epc == null) {
            epc = new ArrayList<EPCN>();
        }
        return this.epc;
    }

}
