package org.oliot.epcis.model.cbv;

public enum GrowingMethodCode {
	CAGE_FREE, CLONED_FOODS, CONVENTIONAL, FARM_RAISED, FIELD_GROWN, FLY_FREE, FREE_RANGE, GRASS_FED, GREENHOUSE,
	HUMANELY_RAISED, HYDROPONIC, INTEGRATED_PEST_MANAGEMENT, ORGANIC, SHADE_GROWN, SUSTAINABLE

}
