package org.oliot.epcis.model.cbv;

import java.util.HashSet;
import java.util.Set;

public class UnloadingPort {
	public static Set<String> codes;

	public static void initialize() {
		codes = new HashSet<String>();
		init1();
		init2();
		init3();
		init4();
		init5();
	}

	private static void init1() {
		codes.addAll(Set.of("AD2", "AD3", "AD4", "AD5", "AD6", "AD7", "AD8", "AEAJ", "AEAZ", "AEDU", "AEFU", "AERK",
				"AESH", "AEUQ", "AFBAL", "AFBAM", "AFBDG", "AFBDS", "AFBGL", "AFDAY", "AFFRA", "AFFYB", "AFGHA",
				"AFGHO", "AFHEL", "AFHER", "AFJOW", "AFKAB", "AFKAN", "AFKAP", "AFKDZ", "AFKHO", "AFKNR", "AFLAG",
				"AFLOG", "AFNAN", "AFNIM", "AFNUR", "AFPAN", "AFPAR", "AFPIA", "AFPKA", "AFSAM", "AFSAR", "AFTAK",
				"AFURU", "AFWAR", "AFZAB", "AG3", "AG4", "AG5", "AG6", "AG7", "AG8", "AG10", "AG11", "AL1", "AL2",
				"AL3", "AL4", "AL5", "AL6", "AL7", "AL8", "AL9", "AL10", "AL11", "AL12", "AMAG", "AMAR", "AMAV", "AMER",
				"AMGR", "AMKT", "AMLO", "AMSH", "AMSU", "AMTV", "AMVD", "AOBGO", "AOBGU", "AOBIE", "AOCAB", "AOCCU",
				"AOCNN", "AOCNO", "AOCUS", "AOHUA", "AOHUI", "AOLNO", "AOLSU", "AOLUA", "AOMAL", "AOMOX", "AONAM",
				"AOUIG", "AOZAI", "ARA", "ARB", "ARC", "ARD", "ARE", "ARF", "ARG", "ARH", "ARJ", "ARK", "ARL", "ARM",
				"ARN", "ARP", "ARQ", "ARR", "ARS", "ART", "ARU", "ARV", "ARW", "ARX", "ARY", "ARZ", "AT1", "AT2", "AT3",
				"AT4", "AT5", "AT6", "AT7", "AT8", "AT9", "AUACT", "AUNSW", "AUNT", "AUQLD", "AUSA", "AUTAS", "AUVIC",
				"AUWA", "AZABS", "AZAGA", "AZAGC", "AZAGM", "AZAGS", "AZAGU", "AZAST", "AZBA", "AZBAB", "AZBAL",
				"AZBAR", "AZBEY", "AZBIL", "AZCAB", "AZCAL", "AZCUL", "AZDAS", "AZFUZ", "AZGA", "AZGAD", "AZGOR",
				"AZGOY", "AZGYG", "AZHAC", "AZIMI", "AZISM", "AZKAL", "AZKAN", "AZKUR", "AZLA", "AZLAC", "AZLAN",
				"AZLER", "AZMAS", "AZMI", "AZNA", "AZNEF", "AZNV", "AZNX", "AZOGU", "AZORD", "AZQAB", "AZQAX", "AZQAZ",
				"AZQBA", "AZQBI", "AZQOB", "AZQUS", "AZSA", "AZSAB", "AZSAD", "AZSAH", "AZSAK", "AZSAL", "AZSAR",
				"AZSAT", "AZSBN", "AZSIY", "AZSKR", "AZSM", "AZSMI", "AZSMX", "AZSR", "AZSUS", "AZTAR", "AZTOV",
				"AZUCA", "AZXA", "AZXAC", "AZXCI", "AZXIZ", "AZXVD", "AZYAR", "AZYE", "AZYEV", "AZZAN", "AZZAQ",
				"AZZAR", "BABIH", "BABRC", "BASRP", "BB1", "BB2", "BB3", "BB4", "BB5", "BB6", "BB7", "BB8", "BB9",
				"BB10", "BB11", "BD1", "BD2", "BD3", "BD4", "BD5", "BD6", "BD7", "BD8", "BD9", "BD10", "BD11", "BD12",
				"BD13", "BD14", "BD15", "BD16", "BD17", "BD18", "BD19", "BD20", "BD21", "BD22", "BD23", "BD24", "BD25",
				"BD26", "BD27", "BD28", "BD29", "BD30", "BD31", "BD32", "BD33", "BD34", "BD35", "BD36", "BD37", "BD38",
				"BD39", "BD40", "BD41", "BD42", "BD43", "BD44", "BD45", "BD46", "BD47", "BD48", "BD49", "BD50", "BD51",
				"BD52", "BD53", "BD54", "BD55", "BD56", "BD57", "BD58", "BD59", "BD60", "BD61", "BD62", "BD63", "BD64",
				"BEBRU", "BEVAN", "BEVBR", "BEVLI", "BEVOV", "BEVWV", "BEWBR", "BEWHT", "BEWLG", "BEWLX", "BEWNA",
				"BFBAL", "BFBAM", "BFBAN", "BFBAZ", "BFBGR", "BFBLG", "BFBLK", "BFCOM", "BFGAN", "BFGNA", "BFGOU",
				"BFHOU", "BFIOB", "BFKAD", "BFKEN", "BFKMD", "BFKMP", "BFKOP", "BFKOS", "BFKOT", "BFKOW", "BFLER",
				"BFLOR", "BFMOU", "BFNAM", "BFNAO", "BFNAY", "BFNOU", "BFOUB", "BFOUD", "BFPAS", "BFPON", "BFSEN",
				"BFSIS", "BFSMT", "BFSNG", "BFSOM", "BFSOR", "BFTAP", "BFTUI", "BFYAG", "BFYAT", "BFZIR", "BFZON",
				"BFZOU", "BG1", "BG2", "BG3", "BG4", "BG5", "BG6", "BG7", "BG8", "BG9", "BG10", "BG11", "BG12", "BG13",
				"BG14", "BG15", "BG16", "BG17", "BG18", "BG19", "BG20", "BG21", "BG22", "BG23", "BG24", "BG25", "BG26",
				"BG27", "BG28", "BH13", "BH14", "BH15", "BH17", "BIBB", "BIBL", "BIBM", "BIBR", "BICA", "BICI", "BIGI",
				"BIKI", "BIKR", "BIKY", "BIMA", "BIMU", "BIMW", "BIMY", "BING", "BIRM", "BIRT", "BIRY", "BJAK", "BJAL",
				"BJAQ", "BJBO", "BJCO", "BJDO", "BJKO", "BJLI", "BJMO", "BJOU", "BJPL", "BJZO", "BNBE", "BNBM", "BNTE",
				"BNTU", "BOB", "BOC", "BOH", "BOL", "BON", "BOO", "BOP", "BOS", "BOT", "BQBO", "BQSA", "BQSE", "BRAC",
				"BRAL", "BRAM", "BRAP", "BRBA", "BRCE", "BRDF", "BRES", "BRGO", "BRMA", "BRMG", "BRMS", "BRMT", "BRPA",
				"BRPB", "BRPE", "BRPI", "BRPR", "BRRJ", "BRRN", "BRRO", "BRRR", "BRRS", "BRSC", "BRSE", "BRSP", "BRTO",
				"BSAK", "BSBI", "BSBP", "BSBY", "BSCE", "BSCI", "BSCK", "BSCO", "BSCS", "BSEG", "BSEX", "BSFP", "BSGC",
				"BSHI", "BSHT", "BSIN", "BSLI", "BSMC", "BSMG", "BSMI", "BSNE", "BSNO", "BSNP", "BSNS", "BSRC", "BSRI",
				"BSSA", "BSSE", "BSSO", "BSSS", "BSSW", "BSWG", "BT11", "BT12", "BT13", "BT14", "BT15", "BT21", "BT22",
				"BT23", "BT24", "BT31", "BT32", "BT33", "BT34", "BT41", "BT42", "BT43", "BT44", "BT45", "BTGA", "BTTY",
				"BWCE", "BWCH", "BWFR", "BWGA", "BWGH", "BWJW", "BWKG", "BWKL", "BWKW", "BWLO", "BWNE", "BWNW", "BWSE",
				"BWSO", "BWSP", "BWST", "BYBR", "BYHM", "BYHO", "BYHR", "BYMA", "BYMI", "BYVI", "BZBZ", "BZCY", "BZCZL",
				"BZOW", "BZSC", "BZTOL", "CAAB", "CABC", "CAMB", "CANB", "CANL", "CANS", "CANT", "CANU", "CAON", "CAPE",
				"CAQC", "CASK", "CAYT", "CDBC", "CDBU", "CDEQ", "CDHK", "CDHL", "CDHU", "CDIT", "CDKC", "CDKE", "CDKG",
				"CDKL", "CDKN", "CDKS", "CDLO", "CDLU", "CDMA", "CDMN", "CDMO", "CDNK", "CDNU", "CDSA", "CDSK", "CDSU",
				"CDTA", "CDTO", "CDTU", "CFAC", "CFBB", "CFBGF", "CFBK", "CFHK", "CFHM", "CFHS", "CFKB", "CFKG", "CFLB",
				"CFMB", "CFMP", "CFNM", "CFOP", "CFSE", "CFUK", "CFVK", "CG11", "CG12", "CG13", "CG14", "CG15", "CG16",
				"CG2", "CG5", "CG7", "CG8", "CG9", "CGBZV", "CHAG", "CHAI", "CHAR", "CHBE", "CHBL", "CHBS", "CHFR",
				"CHGE", "CHGL", "CHGR", "CHJU", "CHLU", "CHNE", "CHNW", "CHOW", "CHSG", "CHSH", "CHSO", "CHSZ", "CHTG",
				"CHTI", "CHUR", "CHVD", "CHVS", "CHZG", "CHZH", "CIAB", "CIBS", "CICM", "CIDN", "CIGD", "CILC", "CILG",
				"CIMG", "CISM", "CISV", "CIVB", "CIWR", "CIYM", "CIZZ", "CLAI", "CLAN", "CLAP", "CLAR", "CLAT", "CLBI",
				"CLCO", "CLLI", "CLLL", "CLLR", "CLMA", "CLML", "CLNB", "CLRM", "CLTA", "CLVS", "CMAD", "CMCE", "CMEN",
				"CMES", "CMLT", "CMNO", "CMNW", "CMOU", "CMSU", "CMSW", "CNAH", "CNBJ", "CNCQ", "CNFJ", "CNGD", "CNGS",
				"CNGX", "CNGZ", "CNHA", "CNHB", "CNHE", "CNHI", "CNHK", "CNHL", "CNHN", "CNJL", "CNJS", "CNJX", "CNLN",
				"CNMO", "CNNM", "CNNX", "CNQH", "CNSC", "CNSD", "CNSH", "CNSN", "CNSX", "CNTJ", "CNTW", "CNXJ", "CNXZ",
				"CNYN", "CNZJ", "COAMA", "COANT", "COARA", "COATL", "COBOL", "COBOY", "COCAL", "COCAQ", "COCAS",
				"COCAU", "COCES", "COCHO", "COCOR", "COCUN", "CODC", "COGUA", "COGUV", "COHUI", "COLAG", "COMAG",
				"COMET", "CONAR", "CONSA", "COPUT", "COQUI", "CORIS", "COSAN", "COSAP", "COSUC", "COTOL", "COVAC",
				"COVAU", "COVID", "CRA", "CRC", "CRG", "CRH", "CRL", "CRP", "CRSJ", "CU1", "CU2", "CU3", "CU4", "CU5",
				"CU6", "CU7", "CU8", "CU9", "CU10", "CU11", "CU12", "CU13", "CU14", "CU15", "CU16", "CU99", "CVBR",
				"CVBV", "CVCA", "CVCF", "CVCR", "CVMA", "CVMO", "CVPA", "CVPN", "CVPR", "CVRB", "CVRG", "CVRS", "CVSD",
				"CVSF", "CVSL", "CVSM", "CVSO", "CVSS", "CVSV", "CVTA", "CVTS", "CY1", "CY2", "CY3", "CY4", "CY5",
				"CY6", "CZ10", "CZ20", "CZ31", "CZ32", "CZ41", "CZ42", "CZ51", "CZ52", "CZ53", "CZ63", "CZ64", "CZ71",
				"CZ72", "CZ80", "DEBB", "DEBE", "DEBW", "DEBY", "DEHB", "DEHE", "DEHH", "DEMV", "DENI", "DENW", "DERP",
				"DESH", "DESL", "DESN", "DEST", "DETH", "DJAR", "DJAS", "DJDI", "DJDJ", "DJOB", "DJTA", "DK81", "DK82",
				"DK83", "DK84", "DK85", "DM2", "DM3", "DM4", "DM5", "DM6", "DM7", "DM8", "DM9", "DM10", "DM11", "DO1",
				"DO2", "DO3", "DO4", "DO5", "DO6", "DO7", "DO8", "DO9", "DO10", "DO11", "DO12", "DO13", "DO14", "DO15",
				"DO16", "DO17", "DO18", "DO19", "DO20", "DO21", "DO22", "DO23", "DO24", "DO25", "DO26", "DO27", "DO28",
				"DO29", "DO30", "DO31", "DO32", "DO33", "DO34", "DO35", "DO36", "DO37", "DO38", "DO39", "DO40", "DO41",
				"DO42", "DZ1", "DZ2", "DZ3", "DZ4", "DZ5", "DZ6", "DZ7", "DZ8", "DZ9", "DZ10", "DZ11", "DZ12", "DZ13",
				"DZ14", "DZ15", "DZ16", "DZ17", "DZ18", "DZ19", "DZ20", "DZ21", "DZ22", "DZ23", "DZ24", "DZ25", "DZ26",
				"DZ27", "DZ28", "DZ29", "DZ30", "DZ31", "DZ32", "DZ33", "DZ34", "DZ35", "DZ36", "DZ37", "DZ38", "DZ39",
				"DZ40", "DZ41", "DZ42", "DZ43", "DZ44", "DZ45", "DZ46", "DZ47", "DZ48", "ECA", "ECB", "ECC", "ECD",
				"ECE", "ECF", "ECG", "ECH", "ECI", "ECL", "ECM", "ECN", "ECO", "ECP", "ECR", "ECS", "ECSD", "ECSE",
				"ECT", "ECU", "ECW", "ECX", "ECY", "ECZ", "EE37", "EE39", "EE44", "EE49", "EE51", "EE57", "EE59",
				"EE65", "EE67", "EE70", "EE74", "EE78", "EE82", "EE84", "EE86", "EGALX", "EGASN", "EGAST", "EGBA",
				"EGBH", "EGBNS", "EGC", "EGDK", "EGDT", "EGFYM", "EGGH", "EGGZ", "EGIS", "EGJS", "EGKB", "EGKFS",
				"EGKN", "EGLX", "EGMN", "EGMNF", "EGMT", "EGPTS", "EGSHG", "EGSHR", "EGSIN", "EGSUZ", "EGWAD", "ERAN",
				"ERDK", "ERDU", "ERGB"));
	}

	private static void init2() {
		codes.addAll(Set.of("ERMA", "ERSK", "ESA", "ESAB", "ESAL", "ESAV", "ESB", "ESBA", "ESBI", "ESBU", "ESC", "ESCA",
				"ESCC", "ESCE", "ESCO", "ESCR", "ESCS", "ESCU", "ESGC", "ESGI", "ESGR", "ESGU", "ESH", "ESHU", "ESJ",
				"ESL", "ESLE", "ESLO", "ESLU", "ESM", "ESMA", "ESML", "ESMU", "ESNA", "ESO", "ESOR", "ESP", "ESPM",
				"ESPO", "ESS", "ESSA", "ESSE", "ESSG", "ESSO", "ESSS", "EST", "ESTE", "ESTF", "ESTO", "ESV", "ESVA",
				"ESVI", "ESZ", "ESZA", "ETAA", "ETAF", "ETAM", "ETBE", "ETDD", "ETGA", "ETHA", "ETOR", "ETSN", "ETSO",
				"ETTI", "FI1", "FI2", "FI3", "FI4", "FI5", "FI6", "FI7", "FI8", "FI9", "FI10", "FI11", "FI12", "FI13",
				"FI14", "FI15", "FI16", "FI17", "FI18", "FI19", "FJ1", "FJ2", "FJ3", "FJ4", "FJ5", "FJ6", "FJ7", "FJ8",
				"FJ9", "FJ10", "FJ11", "FJ12", "FJ13", "FJ14", "FJR", "FMKSA", "FMPNI", "FMTRK", "FMYAP", "FR1", "FR2",
				"FR3", "FR4", "FR5", "FR6", "FR7", "FR8", "FR9", "FR10", "FR11", "FR12", "FR13", "FR14", "FR15", "FR16",
				"FR17", "FR18", "FR19", "FR21", "FR22", "FR23", "FR24", "FR25", "FR26", "FR27", "FR28", "FR29", "FR2A",
				"FR2B", "FR30", "FR31", "FR32", "FR33", "FR34", "FR35", "FR36", "FR37", "FR38", "FR39", "FR40", "FR41",
				"FR42", "FR43", "FR44", "FR45", "FR46", "FR47", "FR48", "FR49", "FR50", "FR51", "FR52", "FR53", "FR54",
				"FR55", "FR56", "FR57", "FR58", "FR59", "FR60", "FR61", "FR62", "FR63", "FR64", "FR65", "FR66", "FR67",
				"FR68", "FR69", "FR70", "FR71", "FR72", "FR73", "FR74", "FR75", "FR76", "FR77", "FR78", "FR79", "FR80",
				"FR81", "FR82", "FR83", "FR84", "FR85", "FR86", "FR87", "FR88", "FR89", "FR90", "FR91", "FR92", "FR93",
				"FR94", "FR95", "GA1", "GA2", "GA3", "GA4", "GA5", "GA6", "GA7", "GA8", "GA9", "GBABC", "GBABD",
				"GBABE", "GBAGB", "GBAGY", "GBAND", "GBANN", "GBANS", "GBARM", "GBBAS", "GBBBD", "GBBDF", "GBBDG",
				"GBBEN", "GBBEX", "GBBFS", "GBBGE", "GBBGW", "GBBIR", "GBBKM", "GBBMH", "GBBNE", "GBBNH", "GBBNS",
				"GBBOL", "GBBPL", "GBBRC", "GBBRD", "GBBRY", "GBBST", "GBBUR", "GBCAM", "GBCAY", "GBCBF", "GBCCG",
				"GBCGN", "GBCHE", "GBCHW", "GBCLD", "GBCLK", "GBCMA", "GBCMD", "GBCMN", "GBCON", "GBCOV", "GBCRF",
				"GBCRY", "GBCWY", "GBDAL", "GBDBY", "GBDEN", "GBDER", "GBDEV", "GBDGY", "GBDNC", "GBDND", "GBDOR",
				"GBDRS", "GBDUD", "GBDUR", "GBEAL", "GBEAY", "GBEDH", "GBEDU", "GBELN", "GBELS", "GBENF", "GBERW",
				"GBERY", "GBESS", "GBESX", "GBFAL", "GBFIF", "GBFLN", "GBFMO", "GBGAT", "GBGLG", "GBGLS", "GBGRE",
				"GBGWN", "GBHAL", "GBHAM", "GBHAV", "GBHCK", "GBHEF", "GBHIL", "GBHLD", "GBHMF", "GBHNS", "GBHPL",
				"GBHRT", "GBHRW", "GBHRY", "GBIOS", "GBIOW", "GBISL", "GBIVC", "GBKEC", "GBKEN", "GBKHL", "GBKIR",
				"GBKTT", "GBKWL", "GBLAN", "GBLBC", "GBLBH", "GBLCE", "GBLDS", "GBLEC", "GBLEW", "GBLIN", "GBLIV",
				"GBLND", "GBLUT", "GBMAN", "GBMDB", "GBMDW", "GBMEA", "GBMIK", "GBMLN", "GBMON", "GBMRT", "GBMRY",
				"GBMTY", "GBMUL", "GBNAY", "GBNBL", "GBNEL", "GBNET", "GBNFK", "GBNGM", "GBNLK", "GBNLN", "GBNMD",
				"GBNSM", "GBNTH", "GBNTL", "GBNTT", "GBNTY", "GBNWM", "GBNWP", "GBNYK", "GBOLD", "GBORK", "GBOXF",
				"GBPEM", "GBPKN", "GBPLY", "GBPOL", "GBPOR", "GBPOW", "GBPTE", "GBRCC", "GBRCH", "GBRCT", "GBRDB",
				"GBRDG", "GBRFW", "GBRIC", "GBROT", "GBRUT", "GBSAW", "GBSAY", "GBSCB", "GBSFK", "GBSFT", "GBSGC",
				"GBSHF", "GBSHN", "GBSHR", "GBSKP", "GBSLF", "GBSLG", "GBSLK", "GBSND", "GBSOL", "GBSOM", "GBSOS",
				"GBSRY", "GBSTE", "GBSTG", "GBSTH", "GBSTN", "GBSTS", "GBSTT", "GBSTY", "GBSWA", "GBSWD", "GBSWK",
				"GBTAM", "GBTFW", "GBTHR", "GBTOB", "GBTOF", "GBTRF", "GBTWH", "GBVGL", "GBWAR", "GBWBK", "GBWDU",
				"GBWFT", "GBWGN", "GBWIL", "GBWKF", "GBWLL", "GBWLN", "GBWLV", "GBWND", "GBWNM", "GBWOK", "GBWOR",
				"GBWRL", "GBWRT", "GBWRX", "GBWSM", "GBWSX", "GBYOR", "GBZET", "GD1", "GD2", "GD3", "GD4", "GD5", "GD6",
				"GD10", "GEAB", "GEAJ", "GEGU", "GEIM", "GEKA", "GEKK", "GEMM", "GERL", "GESJ", "GESK", "GESZ", "GETB",
				"GHAA", "GHAF", "GHAH", "GHBE", "GHBO", "GHCP", "GHEP", "GHNE", "GHNP", "GHOT", "GHSV", "GHTV", "GHUE",
				"GHUW", "GHWN", "GHWP", "GLAV", "GLKU", "GLQE", "GLQT", "GLSM", "GMB", "GML", "GMM", "GMN", "GMU",
				"GMW", "GNBE", "GNBF", "GNBK", "GNCO", "GNDB", "GNDI", "GNDL", "GNDU", "GNFA", "GNFO", "GNFR", "GNGA",
				"GNGU", "GNKA", "GNKB", "GNKD", "GNKE", "GNKN", "GNKO", "GNKS", "GNLA", "GNLE", "GNLO", "GNMC", "GNMD",
				"GNML", "GNMM", "GNNZ", "GNPI", "GNSI", "GNTE", "GNTO", "GNYO", "GQAN", "GQBN", "GQBS", "GQCS", "GQKN",
				"GQLI", "GQWN", "GRA", "GRB", "GRC", "GRD", "GRE", "GRF", "GRG", "GRH", "GRI", "GRJ", "GRK", "GRL",
				"GRM", "GTAV", "GTBV", "GTCM", "GTCQ", "GTES", "GTGU", "GTHU", "GTIZ", "GTJA", "GTJU", "GTPE", "GTPR",
				"GTQC", "GTQZ", "GTRE", "GTSA", "GTSM", "GTSO", "GTSR", "GTSU", "GTTO", "GTZA", "GWBA", "GWBL", "GWBM",
				"GWBS", "GWCA", "GWGA", "GWOI", "GWQU", "GWTO", "GYBA", "GYCU", "GYDE", "GYEB", "GYES", "GYMA", "GYPM",
				"GYPT", "GYUD", "GYUT", "HNAT", "HNCH", "HNCL", "HNCM", "HNCP", "HNCR", "HNEP", "HNFM", "HNGD", "HNIB",
				"HNIN", "HNLE", "HNLP", "HNOC", "HNOL", "HNSB", "HNVA", "HNYO", "HR1", "HR2", "HR3", "HR4", "HR5",
				"HR6", "HR7", "HR8", "HR9", "HR10", "HR11", "HR12", "HR13", "HR14", "HR15", "HR16", "HR17", "HR18",
				"HR19", "HR20", "HR21", "HTAR", "HTCE", "HTGA", "HTND", "HTNE", "HTNI", "HTNO", "HTOU", "HTSD", "HTSE",
				"HUBA", "HUBC", "HUBE", "HUBK", "HUBU", "HUBZ", "HUCS", "HUDE", "HUDU", "HUEG", "HUER", "HUFE", "HUGS",
				"HUGY", "HUHB", "HUHE", "HUHV", "HUJN", "HUKE", "HUKM", "HUKV", "HUMI", "HUNK", "HUNO", "HUNY", "HUPE",
				"HUPS", "HUSD", "HUSF", "HUSH", "HUSK", "HUSN", "HUSO", "HUSS", "HUST", "HUSZ", "HUTB", "HUTO", "HUVA",
				"HUVE", "HUVM", "HUZA", "HUZE", "IDAC", "IDBA", "IDBB", "IDBE", "IDBT", "IDGO", "IDJA", "IDJB", "IDJI",
				"IDJK", "IDJT", "IDKB", "IDKI", "IDKR", "IDKS", "IDKT", "IDKU", "IDLA", "IDMA", "IDMU", "IDNB", "IDNT",
				"IDPA", "IDPB", "IDRI", "IDSA", "IDSB", "IDSG", "IDSN", "IDSR", "IDSS", "IDST", "IDSU", "IDYO", "IECE",
				"IECN", "IECO", "IECW", "IED", "IEDL", "IEG", "IEKE", "IEKK", "IEKY", "IELD", "IELH", "IELK", "IELM",
				"IELS", "IEMH", "IEMN", "IEMO", "IEOY", "IERN", "IESO", "IETA", "IEWD", "IEWH", "IEWW", "IEWX", "ILD",
				"ILHA", "ILJM", "ILM", "ILTA", "ILZ", "INAN", "INAP", "INAR", "INAS", "INBR", "INCH", "INCT", "INDD",
				"INDL", "INDN", "INGA", "INGJ", "INHP", "INHR", "INJH", "INJK", "INKA", "INKL", "INLA", "INLD", "INMH",
				"INML", "INMN", "INMP", "INMZ", "INNL", "INOR", "INPB", "INPY", "INRJ", "INSK", "INTG", "INTN", "INTR",
				"INUP", "INUT", "INWB", "IQAN", "IQAR", "IQBA", "IQBB", "IQBG", "IQDA", "IQDI", "IQDQ", "IQKA", "IQKI",
				"IQMA", "IQMU", "IQNA", "IQNI", "IQQA", "IQSD", "IQSU", "IQWA", "IR1", "IR2", "IR3", "IR4", "IR5",
				"IR6", "IR7", "IR8", "IR10", "IR11", "IR12", "IR13", "IR14", "IR15", "IR16", "IR17", "IR18", "IR19",
				"IR20", "IR21", "IR22", "IR23", "IR24", "IR25", "IR26", "IR27", "IR28", "IR29", "IR30", "IR31", "IR32",
				"IS1", "IS2", "IS3", "IS4", "IS5", "IS6", "IS7", "IS8", "ITAG", "ITAL", "ITAN", "ITAP", "ITAQ", "ITAR",
				"ITAT", "ITAV", "ITBA", "ITBG", "ITBI", "ITBL", "ITBN", "ITBO", "ITBR", "ITBS", "ITBT", "ITBZ", "ITCA",
				"ITCB", "ITCE", "ITCH", "ITCL", "ITCN", "ITCO", "ITCR", "ITCS", "ITCT", "ITCZ", "ITEN", "ITFC", "ITFE",
				"ITFG", "ITFI", "ITFM", "ITFR", "ITGE", "ITGR", "ITIM", "ITIS", "ITKR", "ITLC", "ITLE", "ITLI", "ITLO",
				"ITLT", "ITLU", "ITMB", "ITMC", "ITME", "ITMI", "ITMN", "ITMO", "ITMS", "ITMT", "ITNA", "ITNO", "ITNU",
				"ITOR", "ITPA", "ITPC", "ITPD", "ITPE", "ITPG", "ITPI", "ITPO", "ITPR", "ITPT", "ITPU", "ITPV", "ITPZ",
				"ITRA", "ITRC", "ITRE", "ITRG", "ITRI", "ITRM", "ITRN", "ITRO", "ITSA", "ITSD", "ITSI", "ITSO", "ITSP",
				"ITSR", "ITSS", "ITSV", "ITTA", "ITTE", "ITTN", "ITTO", "ITTP", "ITTR", "ITTV", "ITVA", "ITVB", "ITVC",
				"ITVE", "ITVI", "ITVR", "ITVT", "ITVV", "JM1", "JM2", "JM3", "JM4", "JM5", "JM6", "JM7", "JM8", "JM9",
				"JM10", "JM11", "JM12", "JM13", "JM14", "JOAJ", "JOAM", "JOAQ", "JOAT", "JOAZ", "JOBA", "JOIR", "JOJA",
				"JOKA", "JOMA", "JOMD", "JOMN", "JP1", "JP2", "JP3", "JP4", "JP5", "JP6", "JP7", "JP8", "JP9", "JP10",
				"JP11", "JP12", "JP13", "JP14", "JP15", "JP16", "JP17", "JP18", "JP19", "JP20", "JP21", "JP22", "JP23",
				"JP24", "JP25", "JP26", "JP27", "JP28", "JP29", "JP30", "JP31", "JP32", "JP33", "JP34", "JP35", "JP36",
				"JP37", "JP38", "JP39", "JP40", "JP41", "JP42", "JP43", "JP44", "JP45", "JP46", "JP47", "KE1", "KE2",
				"KE3", "KE4", "KE5", "KE6", "KE7"));
	}

	private static void init3() {
		codes.addAll(Set.of("KE8", "KE9", "KE10", "KE11", "KE12", "KE13", "KE14", "KE15", "KE16", "KE17", "KE18",
				"KE19", "KE20", "KE21", "KE22", "KE23", "KE24", "KE25", "KE26", "KE27", "KE28", "KE29", "KE30", "KE31",
				"KE32", "KE33", "KE34", "KE35", "KE36", "KE37", "KE38", "KE39", "KE40", "KE41", "KE42", "KE43", "KE44",
				"KE45", "KE46", "KE47", "KGB", "KGC", "KGGB", "KGGO", "KGJ", "KGN", "KGO", "KGT", "KGY", "KH1", "KH10",
				"KH11", "KH12", "KH13", "KH14", "KH15", "KH16", "KH17", "KH18", "KH19", "KH2", "KH20", "KH21", "KH22",
				"KH23", "KH24", "KH25", "KH3", "KH4", "KH5", "KH6", "KH7", "KH8", "KH9", "KIG", "KIL", "KIP", "KMA",
				"KMG", "KMM", "KN1", "KN2", "KN3", "KN4", "KN5", "KN6", "KN7", "KN8", "KN9", "KN10", "KN11", "KN12",
				"KN13", "KN15", "KP1", "KP2", "KP3", "KP4", "KP5", "KP6", "KP7", "KP8", "KP9", "KP10", "KP13", "KP14",
				"KR11", "KR26", "KR27", "KR28", "KR29", "KR30", "KR31", "KR41", "KR42", "KR43", "KR44", "KR45", "KR46",
				"KR47", "KR48", "KR49", "KR50", "KWAH", "KWFA", "KWHA", "KWJA", "KWKU", "KWMU", "KZAKM", "KZAKT",
				"KZALA", "KZALM", "KZAST", "KZATY", "KZBAY", "KZKAR", "KZKUS", "KZKZY", "KZMAN", "KZPAV", "KZSEV",
				"KZSHY", "KZVOS", "KZYUZ", "KZZAP", "KZZHA", "LAAT", "LABK", "LABL", "LACH", "LAHO", "LAKH", "LALM",
				"LALP", "LAOU", "LAPH", "LASL", "LASV", "LAVI", "LAVT", "LAXA", "LAXE", "LAXI", "LAXS", "LBAK", "LBAS",
				"LBBA", "LBBH", "LBBI", "LBJA", "LBJL", "LBNA", "LC1", "LC2", "LC3", "LC5", "LC6", "LC7", "LC8", "LC10",
				"LC11", "LC12", "LI1", "LI2", "LI3", "LI4", "LI5", "LI6", "LI7", "LI8", "LI9", "LI10", "LI11", "LK1",
				"LK11", "LK12", "LK13", "LK2", "LK21", "LK22", "LK23", "LK3", "LK31", "LK32", "LK33", "LK4", "LK41",
				"LK42", "LK43", "LK44", "LK45", "LK5", "LK51", "LK52", "LK53", "LK6", "LK61", "LK62", "LK7", "LK71",
				"LK72", "LK8", "LK81", "LK82", "LK9", "LK91", "LK92", "LRBG", "LRBM", "LRCM", "LRGB", "LRGG", "LRGK",
				"LRGP", "LRLO", "LRMG", "LRMO", "LRMY", "LRNI", "LRRG", "LRRI", "LRSI", "LSA", "LSB", "LSC", "LSD",
				"LSE", "LSF", "LSG", "LSH", "LSJ", "LSK", "LT1", "LT2", "LT3", "LT4", "LT5", "LT6", "LT7", "LT8", "LT9",
				"LT10", "LT11", "LT12", "LT13", "LT14", "LT15", "LT16", "LT17", "LT18", "LT19", "LT20", "LT21", "LT22",
				"LT23", "LT24", "LT25", "LT26", "LT27", "LT28", "LT29", "LT30", "LT31", "LT32", "LT33", "LT34", "LT35",
				"LT36", "LT37", "LT38", "LT39", "LT40", "LT41", "LT42", "LT43", "LT44", "LT45", "LT46", "LT47", "LT48",
				"LT49", "LT50", "LT51", "LT52", "LT53", "LT54", "LT55", "LT56", "LT57", "LT58", "LT59", "LT60", "LTAL",
				"LTKL", "LTKU", "LTMR", "LTPN", "LTSA", "LTTA", "LTTE", "LTUT", "LTVL", "LUCA", "LUCL", "LUDI", "LUEC",
				"LUES", "LUGR", "LULU", "LUME", "LURD", "LURM", "LUVD", "LUWI", "LV1", "LV2", "LV3", "LV4", "LV5",
				"LV6", "LV7", "LV8", "LV9", "LV10", "LV11", "LV12", "LV13", "LV14", "LV15", "LV16", "LV17", "LV18",
				"LV19", "LV20", "LV21", "LV22", "LV23", "LV24", "LV25", "LV26", "LV27", "LV28", "LV29", "LV30", "LV31",
				"LV32", "LV33", "LV34", "LV35", "LV36", "LV37", "LV38", "LV39", "LV40", "LV41", "LV42", "LV43", "LV44",
				"LV45", "LV46", "LV47", "LV48", "LV49", "LV50", "LV51", "LV52", "LV53", "LV54", "LV55", "LV56", "LV57",
				"LV58", "LV59", "LV60", "LV61", "LV62", "LV63", "LV64", "LV65", "LV66", "LV67", "LV68", "LV69", "LV70",
				"LV71", "LV72", "LV73", "LV74", "LV75", "LV76", "LV77", "LV78", "LV79", "LV80", "LV81", "LV82", "LV83",
				"LV84", "LV85", "LV86", "LV87", "LV88", "LV89", "LV90", "LV91", "LV92", "LV93", "LV94", "LV95", "LV96",
				"LV97", "LV98", "LV99", "LV100", "LV101", "LV102", "LV103", "LV104", "LV105", "LV106", "LV107", "LV108",
				"LV109", "LV110", "LVDGV", "LVJEL", "LVJKB", "LVJUR", "LVLPX", "LVREZ", "LVRIX", "LVVEN", "LVVMR",
				"LYBA", "LYBU", "LYDR", "LYGT", "LYJA", "LYJG", "LYJI", "LYJU", "LYKF", "LYMB", "LYMI", "LYMJ", "LYMQ",
				"LYNL", "LYNQ", "LYSB", "LYSR", "LYTB", "LYWA", "LYWD", "LYWS", "LYZA", "MA1", "MA2", "MA3", "MA4",
				"MA5", "MA6", "MA7", "MA8", "MA9", "MA10", "MA11", "MA12", "MAAGD", "MAAOU", "MAASZ", "MAAZI", "MABEM",
				"MABER", "MABES", "MABOD", "MABOM", "MABRR", "MACAS", "MACHE", "MACHI", "MACHT", "MACHT", "MADRI",
				"MAERR", "MAESI", "MAESM", "MAFAH", "MAFES", "MAFIG", "MAFQH", "MAGUE", "MAGUF", "MAHAJ", "MAHAO",
				"MAHOC", "MAIFR", "MAINE", "MAJDI", "MAJRA", "MAKEN", "MAKES", "MAKES", "MAKHE", "MAKHN", "MAKHO",
				"MALAA", "MALAR", "MAMAR", "MAMDF", "MAMED", "MAMEK", "MAMID", "MAMMD", "MAMMN", "MAMOH", "MAMOU",
				"MANAD", "MANOU", "MAOUA", "MAOUD", "MAOUJ", "MAOUZ", "MARAB", "MAREH", "MASAF", "MASAL", "MASEF",
				"MASET", "MASIB", "MASIF", "MASIK", "MASIL", "MASKH", "MASYB", "MATAF", "MATAI", "MATAO", "MATAR",
				"MATAT", "MATAZ", "MATET", "MATIN", "MATIZ", "MATNG", "MATNT", "MAYUS", "MAZAG", "MCCL", "MCCO", "MCFO",
				"MCGA", "MCJE", "MCLA", "MCMA", "MCMC", "MCMG", "MCMO", "MCMU", "MCPH", "MCSD", "MCSO", "MCSP", "MCSR",
				"MCVR", "MDAN", "MDBA", "MDBD", "MDBR", "MDBS", "MDCA", "MDCL", "MDCM", "MDCR", "MDCS", "MDCT", "MDCU",
				"MDDO", "MDDR", "MDDU", "MDED", "MDFA", "MDFL", "MDGA", "MDGL", "MDHI", "MDIA", "MDLE", "MDNI", "MDOC",
				"MDOR", "MDRE", "MDRI", "MDSD", "MDSI", "MDSN", "MDSO", "MDST", "MDSV", "MDTA", "MDTE", "MDUN", "ME1",
				"ME2", "ME3", "ME4", "ME5", "ME6", "ME7", "ME8", "ME9", "ME10", "ME11", "ME12", "ME13", "ME14", "ME15",
				"ME16", "ME17", "ME18", "ME19", "ME20", "ME21", "ME22", "ME23", "ME24", "MGA", "MGD", "MGF", "MGM",
				"MGT", "MGU", "MHALK", "MHALL", "MHARN", "MHAUR", "MHEBO", "MHENI", "MHJAB", "MHJAL", "MHKIL", "MHKWA",
				"MHL", "MHLAE", "MHLIB", "MHLIK", "MHMAJ", "MHMAL", "MHMEJ", "MHMIL", "MHNMK", "MHNMU", "MHRON", "MHT",
				"MHUJA", "MHUTI", "MHWTH", "MHWTJ", "MK101", "MK102", "MK103", "MK104", "MK105", "MK106", "MK107",
				"MK108", "MK109", "MK201", "MK202", "MK203", "MK204", "MK205", "MK205", "MK206", "MK207", "MK208",
				"MK209", "MK210", "MK211", "MK301", "MK303", "MK304", "MK307", "MK308", "MK310", "MK311", "MK312",
				"MK313", "MK401", "MK402", "MK403", "MK404", "MK405", "MK406", "MK407", "MK408", "MK409", "MK410",
				"MK501", "MK502", "MK503", "MK504", "MK505", "MK506", "MK507", "MK508", "MK509", "MK601", "MK602",
				"MK603", "MK604", "MK605", "MK606", "MK607", "MK608", "MK609", "MK701", "MK702", "MK703", "MK704",
				"MK705", "MK706", "MK801", "MK802", "MK803", "MK804", "MK805", "MK806", "MK807", "MK808", "MK809",
				"MK810", "MK811", "MK812", "MK813", "MK814", "MK815", "MK816", "MK817", "ML1", "ML10", "ML2", "ML3",
				"ML4", "ML5", "ML6", "ML7", "ML8", "ML9", "MLBKO", "MM1", "MM2", "MM3", "MM4", "MM5", "MM6", "MM7",
				"MM11", "MM12", "MM13", "MM14", "MM15", "MM16", "MM17", "MM18", "MN35", "MN37", "MN39", "MN41", "MN43",
				"MN46", "MN47", "MN49", "MN51", "MN53", "MN55", "MN57", "MN59", "MN61", "MN63", "MN64", "MN65", "MN67",
				"MN69", "MN71", "MN73", "MN1", "MR1", "MR2", "MR3", "MR4", "MR5", "MR6", "MR7", "MR8", "MR9", "MR10",
				"MR11", "MR12", "MR13", "MR14", "MR15", "MT1", "MT2", "MT3", "MT4", "MT5", "MT6", "MT7", "MT8", "MT9",
				"MT10", "MT11", "MT12", "MT13", "MT14", "MT15", "MT16", "MT17", "MT18", "MT19", "MT20", "MT21", "MT22",
				"MT23", "MT24", "MT25", "MT26", "MT27", "MT28", "MT29", "MT30", "MT31", "MT32", "MT33", "MT34", "MT35",
				"MT36", "MT37", "MT38", "MT39", "MT40", "MT41", "MT42", "MT43", "MT44", "MT45", "MT46", "MT47", "MT48",
				"MT49", "MT50", "MT51", "MT52", "MT53", "MT54", "MT55", "MT56", "MT57", "MT58", "MT59", "MT60", "MT61",
				"MT62", "MT63", "MT64", "MT65", "MT66", "MT67", "MT68", "MUAG", "MUBL", "MUBR", "MUCC", "MUCU", "MUFL",
				"MUGP", "MUMO", "MUPA", "MUPL", "MUPU", "MUPW", "MUQB", "MURO", "MURR", "MUSA", "MUVP", "MV0", "MV1",
				"MV2", "MV3", "MV4", "MV5", "MV7", "MV8", "MV12", "MV13", "MV14", "MV17", "MV20", "MV23", "MV24",
				"MV25", "MV26", "MV27", "MV28", "MV29", "MVMLE", "MWBA", "MWBL", "MWC", "MWCK", "MWCR", "MWCT", "MWDE",
				"MWDO", "MWKR", "MWKS", "MWLI", "MWLK", "MWMC", "MWMG", "MWMH", "MWMU", "MWMW", "MWMZ", "MWN", "MWNB",
				"MWNE", "MWNI", "MWNK", "MWNS", "MWNU", "MWPH", "MWRU", "MWS", "MWSA", "MWTH", "MWZO", "MXAGU", "MXBCN",
				"MXBCS", "MXCAM", "MXCHH", "MXCHP", "MXCMX", "MXCOA", "MXCOL", "MXDUR", "MXGRO", "MXGUA", "MXHID",
				"MXJAL", "MXMEX", "MXMIC", "MXMOR", "MXNAY", "MXNLE", "MXOAX", "MXPUE", "MXQUE", "MXROO", "MXSIN",
				"MXSLP", "MXSON", "MXTAB", "MXTAM", "MXTLA", "MXVER", "MXYUC", "MXZAC", "MY1", "MY2", "MY3", "MY4",
				"MY5", "MY6", "MY7", "MY8", "MY9"));
	}

	private static void init4() {
		codes.addAll(Set.of("MY10", "MY11", "MY12", "MY13", "MY14", "MY15", "MY16", "MZA", "MZB", "MZG", "MZI", "MZL",
				"MZMPM", "MZN", "MZP", "MZQ", "MZS", "MZT", "NACA", "NAER", "NAHA", "NAKA", "NAKE", "NAKH", "NAKU",
				"NAKW", "NAOD", "NAOH", "NAON", "NAOS", "NAOT", "NAOW", "NE1", "NE2", "NE3", "NE4", "NE5", "NE6", "NE7",
				"NE8", "NGAB", "NGAD", "NGAK", "NGAN", "NGBA", "NGBE", "NGBO", "NGBY", "NGCR", "NGDE", "NGEB", "NGED",
				"NGEK", "NGEN", "NGFC", "NGGO", "NGIM", "NGJI", "NGKD", "NGKE", "NGKN", "NGKO", "NGKT", "NGKW", "NGLA",
				"NGNA", "NGNI", "NGOG", "NGON", "NGOS", "NGOY", "NGPL", "NGRI", "NGSO", "NGTA", "NGYO", "NGZA", "NIAN",
				"NIAS", "NIBO", "NICA", "NICI", "NICO", "NIES", "NIGR", "NIJI", "NILE", "NIMD", "NIMN", "NIMS", "NIMT",
				"NINS", "NIRI", "NISJ", "NLDR", "NLFL", "NLFR", "NLGE", "NLGR", "NLLI", "NLNB", "NLNH", "NLOV", "NLUT",
				"NLZE", "NLZH", "NO1", "NO2", "NO3", "NO4", "NO5", "NO6", "NO7", "NO8", "NO9", "NO10", "NO11", "NO12",
				"NO14", "NO15", "NO18", "NO19", "NO20", "NO21", "NO22", "NO50", "NPBA", "NPBH", "NPDH", "NPGA", "NPJA",
				"NPKA", "NPKO", "NPLU", "NPMA", "NPME", "NPNA", "NPP1", "NPP2", "NPP3", "NPP4", "NPP5", "NPP6", "NPP7",
				"NPRA", "NPSA", "NPSE", "NR1", "NR2", "NR3", "NR4", "NR5", "NR6", "NR7", "NR8", "NR9", "NR10", "NR11",
				"NR12", "NR13", "NR14", "NZAUK", "NZBOP", "NZCAN", "NZCIT", "NZGIS", "NZHKB", "NZMBH", "NZMWT", "NZNSN",
				"NZNTL", "NZOTA", "NZSTL", "NZTAS", "NZTKI", "NZWGN", "NZWKO", "NZWTC", "OMBJ", "OMBS", "OMBU", "OMDA",
				"OMMA", "OMMU", "OMSJ", "OMSS", "OMWU", "OMZA", "OMZU", "PA1", "PA10", "PA2", "PA3", "PA4", "PA5",
				"PA6", "PA7", "PA8", "PA9", "PAEM", "PAKY", "PANB", "PEAMA", "PEANC", "PEAPU", "PEARE", "PEAYA",
				"PECAJ", "PECAL", "PECUS", "PEHUC", "PEHUV", "PEICA", "PEJUN", "PELAL", "PELAM", "PELIM", "PELMA",
				"PELOR", "PEMDD", "PEMOQ", "PEPAS", "PEPIU", "PEPUN", "PESAM", "PETAC", "PETUM", "PEUCA", "PGCPK",
				"PGCPM", "PGEBR", "PGEHG", "PGEPW", "PGESW", "PGGPK", "PGHLA", "PGJWK", "PGMBA", "PGMPL", "PGMPM",
				"PGMRL", "PGNCD", "PGNIK", "PGNPP", "PGNSB", "PGSAN", "PGSHM", "PGWBK", "PGWHM", "PGWPD", "PH0",
				"PHABR", "PHAGN", "PHAGS", "PHAKL", "PHALB", "PHANT", "PHAPA", "PHAUR", "PHBAN", "PHBAS", "PHBEN",
				"PHBIL", "PHBOH", "PHBTG", "PHBTN", "PHBUK", "PHBUL", "PHCAG", "PHCAM", "PHCAN", "PHCAP", "PHCAS",
				"PHCAT", "PHCAV", "PHCEB", "PHCOM", "PHDAO", "PHDAS", "PHDAV", "PHDIN", "PHDVO", "PHEAS", "PHGUI",
				"PHIFU", "PHILI", "PHILN", "PHILS", "PHISA", "PHKAL", "PHLAG", "PHLAN", "PHLAS", "PHLEY", "PHLUN",
				"PHMAD", "PHMAG", "PHMAS", "PHMDC", "PHMDR", "PHMOU", "PHMSC", "PHMSR", "PHNCO", "PHNEC", "PHNER",
				"PHNSA", "PHNUE", "PHNUV", "PHPAM", "PHPAN", "PHPLW", "PHQUE", "PHQUI", "PHRIZ", "PHROM", "PHSAR",
				"PHSCO", "PHSIG", "PHSLE", "PHSLU", "PHSOR", "PHSUK", "PHSUN", "PHSUR", "PHTAR", "PHTAW", "PHWSA",
				"PHZAN", "PHZAS", "PHZMB", "PHZSI", "PKBA", "PKGB", "PKIS", "PKJK", "PKKP", "PKPB", "PKSD", "PL2",
				"PL4", "PL6", "PL8", "PL10", "PL12", "PL14", "PL16", "PL18", "PL20", "PL22", "PL24", "PL26", "PL28",
				"PL30", "PL32", "PSBTH", "PSDEB", "PSGZA", "PSHBN", "PSJEM", "PSJRH", "PSKYS", "PSNBS", "PSNGZ",
				"PSQQA", "PSRBH", "PSRFH", "PSSLT", "PSTBS", "PSTKM", "PT1", "PT2", "PT3", "PT4", "PT5", "PT6", "PT7",
				"PT8", "PT9", "PT10", "PT11", "PT12", "PT13", "PT14", "PT15", "PT16", "PT17", "PT18", "PT20", "PT30",
				"PW2", "PW4", "PW10", "PW50", "PW100", "PW150", "PW212", "PW214", "PW218", "PW222", "PW224", "PW226",
				"PW227", "PW228", "PW350", "PW370", "PY1", "PY10", "PY11", "PY12", "PY13", "PY14", "PY15", "PY16",
				"PY19", "PY2", "PY3", "PY4", "PY5", "PY6", "PY7", "PY8", "PY9", "PYASU", "QADA", "QAKH", "QAMS", "QARA",
				"QASH", "QAUS", "QAWA", "QAZA", "ROAB", "ROAG", "ROAR", "ROB", "ROBC", "ROBH", "ROBN", "ROBR", "ROBT",
				"ROBV", "ROBZ", "ROCJ", "ROCL", "ROCS", "ROCT", "ROCV", "RODB", "RODJ", "ROGJ", "ROGL", "ROGR", "ROHD",
				"ROHR", "ROIF", "ROIL", "ROIS", "ROMH", "ROMM", "ROMS", "RONT", "ROOT", "ROPH", "ROSB", "ROSJ", "ROSM",
				"ROSV", "ROTL", "ROTM", "ROTR", "ROVL", "ROVN", "ROVS", "RS0", "RS1", "RS2", "RS3", "RS4", "RS5", "RS6",
				"RS7", "RS8", "RS9", "RS10", "RS11", "RS12", "RS13", "RS14", "RS15", "RS16", "RS17", "RS18", "RS19",
				"RS20", "RS21", "RS22", "RS23", "RS24", "RS25", "RS26", "RS27", "RS28", "RS29", "RSKM", "RSVO", "RUAD",
				"RUAL", "RUALT", "RUAMU", "RUARK", "RUAST", "RUBA", "RUBEL", "RUBRY", "RUBU", "RUCE", "RUCHE", "RUCHU",
				"RUCU", "RUDA", "RUIN", "RUIRK", "RUIVA", "RUKAM", "RUKB", "RUKC", "RUKDA", "RUKEM", "RUKGD", "RUKGN",
				"RUKHA", "RUKHM", "RUKIR", "RUKK", "RUKL", "RUKLU", "RUKO", "RUKOS", "RUKR", "RUKRS", "RUKYA", "RULEN",
				"RULIP", "RUMAG", "RUME", "RUMO", "RUMOS", "RUMOW", "RUMUR", "RUNEN", "RUNGR", "RUNIZ", "RUNVS",
				"RUOMS", "RUORE", "RUORL", "RUPER", "RUPNZ", "RUPRI", "RUPSK", "RUROS", "RURYA", "RUSA", "RUSAK",
				"RUSAM", "RUSAR", "RUSE", "RUSMO", "RUSPE", "RUSTA", "RUSVE", "RUTA", "RUTAM", "RUTOM", "RUTUL",
				"RUTVE", "RUTY", "RUTYU", "RUUD", "RUULY", "RUVGG", "RUVLA", "RUVLG", "RUVOR", "RUYAN", "RUYAR",
				"RUYEV", "RUZAB", "RW1", "RW2", "RW3", "RW4", "RW5", "SA1", "SA2", "SA3", "SA4", "SA5", "SA6", "SA7",
				"SA8", "SA9", "SA10", "SA11", "SA12", "SA14", "SBCE", "SBCH", "SBCT", "SBGU", "SBIS", "SBMK", "SBML",
				"SBRB", "SBTE", "SBWE", "SC1", "SC2", "SC3", "SC4", "SC5", "SC6", "SC7", "SC8", "SC9", "SC10", "SC11",
				"SC12", "SC13", "SC14", "SC15", "SC16", "SC17", "SC18", "SC19", "SC20", "SC21", "SC22", "SC23", "SC24",
				"SC25", "SDDC", "SDDE", "SDDN", "SDDS", "SDDW", "SDGD", "SDGK", "SDGZ", "SDKA", "SDKH", "SDKN", "SDKS",
				"SDNB", "SDNO", "SDNR", "SDNW", "SDRS", "SDSI", "SEAB", "SEAC", "SEBD", "SEC", "SED", "SEE", "SEF",
				"SEG", "SEH", "SEI", "SEK", "SEM", "SEN", "SEO", "SES", "SET", "SEU", "SEW", "SEX", "SEY", "SEZ", "SG1",
				"SG2", "SG3", "SG4", "SG5", "SHAC", "SHHL", "SHTA", "SI1", "SI2", "SI3", "SI4", "SI5", "SI6", "SI7",
				"SI8", "SI9", "SI10", "SI11", "SI12", "SI13", "SI14", "SI15", "SI16", "SI17", "SI18", "SI19", "SI20",
				"SI21", "SI22", "SI23", "SI24", "SI25", "SI26", "SI27", "SI28", "SI29", "SI30", "SI31", "SI32", "SI33",
				"SI34", "SI35", "SI36", "SI37", "SI38", "SI39", "SI40", "SI41", "SI42", "SI43", "SI44", "SI45", "SI46",
				"SI47", "SI48", "SI49", "SI50", "SI51", "SI52", "SI53", "SI54", "SI55", "SI56", "SI57", "SI58", "SI59",
				"SI60", "SI61", "SI62", "SI63", "SI64", "SI65", "SI66", "SI67", "SI68", "SI69", "SI70", "SI71", "SI72",
				"SI73", "SI74", "SI75", "SI76", "SI77", "SI78", "SI79", "SI80", "SI81", "SI82", "SI83", "SI84", "SI85",
				"SI86", "SI87", "SI88", "SI89", "SI90", "SI91", "SI92", "SI93", "SI94", "SI95", "SI96", "SI97", "SI98",
				"SI99", "SI100", "SI101", "SI102", "SI103", "SI104", "SI105", "SI106", "SI107", "SI108", "SI109",
				"SI110", "SI111", "SI112", "SI113", "SI114", "SI115", "SI116", "SI117", "SI118", "SI119", "SI120",
				"SI121", "SI122", "SI123", "SI124", "SI125", "SI126", "SI127", "SI128", "SI129", "SI130", "SI131",
				"SI132", "SI133", "SI134", "SI135", "SI136", "SI137", "SI138", "SI139", "SI140", "SI141", "SI142",
				"SI143", "SI144", "SI146", "SI147", "SI148", "SI149", "SI150", "SI151", "SI152", "SI153", "SI154",
				"SI155", "SI156", "SI157", "SI158", "SI159", "SI160", "SI161", "SI162", "SI163", "SI164", "SI165",
				"SI166", "SI167", "SI168", "SI169", "SI170", "SI171", "SI172", "SI173", "SI174", "SI175", "SI176",
				"SI177", "SI178", "SI179", "SI180", "SI181", "SI182", "SI183", "SI184", "SI185", "SI186", "SI187",
				"SI188", "SI189", "SI190", "SI191", "SI192", "SI193", "SI194", "SI195", "SI196", "SI197", "SI198",
				"SI199", "SI200", "SI201", "SI202", "SI203", "SI204", "SI205", "SI206", "SI207", "SI208", "SI209",
				"SI210", "SI211", "SI212", "SI213", "SKBC", "SKBL", "SKKI", "SKNI", "SKPV", "SKTA", "SKTC", "SKZI",
				"SLE", "SLN", "SLNW", "SLS", "SLW", "SM1", "SM2", "SM3", "SM4", "SM5", "SM6", "SM7", "SM8", "SM9",
				"SNDB", "SNDK", "SNFK", "SNKA", "SNKD", "SNKE", "SNKL", "SNLG", "SNMT", "SNSE", "SNSL", "SNTC", "SNTH",
				"SNZG", "SOAW", "SOBK", "SOBN", "SOBR", "SOBY", "SOGA", "SOGE", "SOHI", "SOJD", "SOJH", "SOMU", "SONU",
				"SOSA", "SOSD", "SOSH", "SOSO", "SOTO", "SOWO", "SRBR", "SRCM", "SRCR", "SRMA", "SRNI", "SRPM", "SRPR",
				"SRSA", "SRSI", "SRWA", "SSBN", "SSBW", "SSEC", "SSEE", "SSEW", "SSJG", "SSLK", "SSNU", "SSUY", "SSWR",
				"STP", "STS", "SVAH", "SVCA", "SVCH", "SVCU", "SVLI", "SVMO", "SVPA", "SVSA", "SVSM", "SVSO", "SVSS",
				"SVSV", "SVUN", "SVUS", "SYDI", "SYDR", "SYDY", "SYHA", "SYHI", "SYHL", "SYHM", "SYID", "SYLA"));
	}

	private static void init5() {
		codes.addAll(Set.of("SYQU", "SYRA", "SYRD", "SYSU", "SYTA", "SZHH", "SZLU", "SZMA", "SZSH", "TDBA", "TDBG",
				"TDBO", "TDCB", "TDEE", "TDEO", "TDGR", "TDHL", "TDKA", "TDLC", "TDLO", "TDLR", "TDMA", "TDMC", "TDME",
				"TDMO", "TDND", "TDOD", "TDSA", "TDSI", "TDTA", "TDTI", "TDWF", "TGC", "TGK", "TGM", "TGP", "TGS",
				"TH10", "TH11", "TH12", "TH13", "TH14", "TH15", "TH16", "TH17", "TH18", "TH19", "TH20", "TH21", "TH22",
				"TH23", "TH24", "TH25", "TH26", "TH27", "TH30", "TH31", "TH32", "TH33", "TH34", "TH35", "TH36", "TH37",
				"TH38", "TH39", "TH40", "TH41", "TH42", "TH43", "TH44", "TH45", "TH46", "TH47", "TH48", "TH49", "TH50",
				"TH51", "TH52", "TH53", "TH54", "TH55", "TH56", "TH57", "TH58", "TH60", "TH61", "TH62", "TH63", "TH64",
				"TH65", "TH66", "TH67", "TH70", "TH71", "TH72", "TH73", "TH74", "TH75", "TH76", "TH77", "TH80", "TH81",
				"TH82", "TH83", "TH84", "TH85", "TH86", "TH90", "TH91", "TH92", "TH93", "TH94", "TH95", "TH96", "THS",
				"TJDU", "TJGB", "TJKT", "TJRA", "TJSU", "TLAL", "TLAN", "TLBA", "TLBO", "TLCO", "TLDI", "TLER", "TLLA",
				"TLLI", "TLMF", "TLMT", "TLOE", "TLVI", "TMA", "TMB", "TMD", "TML", "TMM", "TMS", "TN11", "TN12",
				"TN13", "TN14", "TN21", "TN22", "TN23", "TN31", "TN32", "TN33", "TN34", "TN41", "TN42", "TN43", "TN51",
				"TN52", "TN53", "TN61", "TN71", "TN72", "TN73", "TN81", "TN82", "TN83", "TO1", "TO2", "TO3", "TO4",
				"TO5", "TR1", "TR2", "TR3", "TR4", "TR5", "TR6", "TR7", "TR8", "TR9", "TR10", "TR11", "TR12", "TR13",
				"TR14", "TR15", "TR16", "TR17", "TR18", "TR19", "TR20", "TR21", "TR22", "TR23", "TR24", "TR25", "TR26",
				"TR27", "TR28", "TR29", "TR30", "TR31", "TR32", "TR33", "TR34", "TR35", "TR36", "TR37", "TR38", "TR39",
				"TR40", "TR41", "TR42", "TR43", "TR44", "TR45", "TR46", "TR47", "TR48", "TR49", "TR50", "TR51", "TR52",
				"TR53", "TR54", "TR55", "TR56", "TR57", "TR58", "TR59", "TR60", "TR61", "TR62", "TR63", "TR64", "TR65",
				"TR66", "TR67", "TR68", "TR69", "TR70", "TR71", "TR72", "TR73", "TR74", "TR75", "TR76", "TR77", "TR78",
				"TR79", "TR80", "TR81", "TTARI", "TTCHA", "TTCTT", "TTDMN", "TTMRC", "TTPED", "TTPOS", "TTPRT", "TTPTF",
				"TTSFO", "TTSGE", "TTSIP", "TTSJL", "TTTOB", "TTTUP", "TVFUN", "TVNIT", "TVNIU", "TVNKF", "TVNKL",
				"TVNMA", "TVNMG", "TVVAI", "TWCHA", "TWCYI", "TWCYQ", "TWHSQ", "TWHSZ", "TWHUA", "TWILA", "TWKEE",
				"TWKHH", "TWKIN", "TWLIE", "TWMIA", "TWNAN", "TWNWT", "TWPEN", "TWPIF", "TWTAO", "TWTNN", "TWTPE",
				"TWTTT", "TWTXG", "TWYUN", "TZ1", "TZ2", "TZ3", "TZ4", "TZ5", "TZ6", "TZ7", "TZ8", "TZ9", "TZ10",
				"TZ11", "TZ12", "TZ13", "TZ14", "TZ15", "TZ16", "TZ17", "TZ18", "TZ19", "TZ20", "TZ21", "TZ22", "TZ23",
				"TZ24", "TZ25", "TZ26", "TZ27", "TZ28", "TZ29", "TZ30", "TZ31", "UA5", "UA7", "UA9", "UA12", "UA14",
				"UA18", "UA21", "UA23", "UA26", "UA30", "UA32", "UA35", "UA40", "UA43", "UA46", "UA48", "UA51", "UA53",
				"UA56", "UA59", "UA61", "UA63", "UA65", "UA68", "UA71", "UA74", "UA77", "UG101", "UG102", "UG103",
				"UG104", "UG105", "UG106", "UG107", "UG108", "UG109", "UG110", "UG111", "UG112", "UG113", "UG114",
				"UG115", "UG116", "UG117", "UG118", "UG119", "UG120", "UG121", "UG122", "UG123", "UG124", "UG125",
				"UG126", "UG201", "UG202", "UG203", "UG204", "UG205", "UG206", "UG207", "UG208", "UG209", "UG210",
				"UG211", "UG212", "UG213", "UG215", "UG216", "UG217", "UG218", "UG219", "UG220", "UG221", "UG222",
				"UG223", "UG224", "UG225", "UG226", "UG227", "UG228", "UG229", "UG230", "UG231", "UG232", "UG233",
				"UG234", "UG235", "UG236", "UG244", "UG301", "UG302", "UG303", "UG304", "UG305", "UG306", "UG307",
				"UG308", "UG309", "UG310", "UG311", "UG312", "UG313", "UG314", "UG315", "UG316", "UG317", "UG318",
				"UG319", "UG320", "UG321", "UG325", "UG326", "UG327", "UG328", "UG329", "UG330", "UG331", "UG332",
				"UG333", "UG334", "UG401", "UG402", "UG403", "UG404", "UG405", "UG406", "UG407", "UG408", "UG409",
				"UG410", "UG411", "UG412", "UG413", "UG414", "UG415", "UG416", "UG417", "UG418", "UG419", "UG420",
				"UG421", "UG422", "UG423", "UG424", "UG425", "UG426", "UG427", "UG428", "UG429", "UG430", "UG431",
				"UG432", "UM67", "UM71", "UM76", "UM79", "UM81", "UM84", "UM86", "UM89", "UM95", "USAK", "USAL", "USAR",
				"USAS", "USAZ", "USCA", "USCO", "USCT", "USDC", "USDE", "USFL", "USGA", "USGU", "USHI", "USIA", "USID",
				"USIL", "USIN", "USKS", "USKY", "USLA", "USMA", "USMD", "USME", "USMI", "USMN", "USMO", "USMP", "USMS",
				"USMT", "USNC", "USND", "USNE", "USNH", "USNJ", "USNM", "USNV", "USNY", "USOH", "USOK", "USOR", "USPA",
				"USPR", "USRI", "USSC", "USSD", "USTN", "USTX", "USUM", "USUT", "USVA", "USVI", "USVT", "USWA", "USWI",
				"USWV", "USWY", "UYAR", "UYCA", "UYCL", "UYCO", "UYDU", "UYFD", "UYFS", "UYLA", "UYMA", "UYMO", "UYPA",
				"UYRN", "UYRO", "UYRV", "UYSA", "UYSJ", "UYSO", "UYTA", "UYTT", "UZAN", "UZBU", "UZFA", "UZJI", "UZKH",
				"UZNG", "UZNW", "UZQA", "UZQR", "UZSA", "UZSI", "UZSU", "UZTK", "UZTO", "UZXO", "VC1", "VC2", "VC3",
				"VC4", "VC5", "VC6", "VEA", "VEB", "VEC", "VED", "VEE", "VEF", "VEG", "VEH", "VEI", "VEJ", "VEK", "VEL",
				"VEM", "VEN", "VEO", "VEP", "VER", "VES", "VET", "VEU", "VEV", "VEW", "VEX", "VEY", "VEZ", "VN1", "VN2",
				"VN3", "VN4", "VN5", "VN6", "VN7", "VN9", "VN13", "VN14", "VN18", "VN20", "VN21", "VN22", "VN23",
				"VN24", "VN25", "VN26", "VN27", "VN28", "VN29", "VN30", "VN31", "VN32", "VN33", "VN34", "VN35", "VN36",
				"VN37", "VN39", "VN40", "VN41", "VN43", "VN44", "VN45", "VN46", "VN47", "VN49", "VN50", "VN51", "VN52",
				"VN53", "VN54", "VN55", "VN56", "VN57", "VN58", "VN59", "VN61", "VN63", "VN66", "VN67", "VN68", "VN69",
				"VN70", "VN71", "VN72", "VN73", "VNCT", "VNDN", "VNHN", "VNHP", "VNSG", "VUMAP", "VUPAM", "VUSAM",
				"VUSEE", "VUTAE", "VUTOB", "WSAA", "WSAL", "WSAT", "WSFA", "WSGE", "WSGI", "WSPA", "WSSA", "WSTU",
				"WSVF", "WSVS", "YEAB", "YEAD", "YEAM", "YEBA", "YEDA", "YEDH", "YEHD", "YEHJ", "YEHU", "YEIB", "YEJA",
				"YELA", "YEMA", "YEMR", "YEMW", "YERA", "YESA", "YESD", "YESH", "YESN", "YESU", "YETA", "ZAEC", "ZAFS",
				"ZAGP", "ZAKZN", "ZALP", "ZAMP", "ZANC", "ZANW", "ZAWC", "ZM1", "ZM2", "ZM3", "ZM4", "ZM5", "ZM6",
				"ZM7", "ZM8", "ZM9", "ZM10", "ZWBU", "ZWHA", "ZWMA", "ZWMC", "ZWME", "ZWMI", "ZWMN", "ZWMS", "ZWMV",
				"ZWMW"));
	}
}
