//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:39:48 PM KST 
//


package org.oliot.model.oliot;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ScopeInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "ScopeInformation");
    private final static QName _CorrelationInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "CorrelationInformation");
    private final static QName _StandardBusinessDocumentHeader_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocumentHeader");
    private final static QName _BusinessService_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "BusinessService");
    private final static QName _StandardBusinessDocument_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocument");
    private final static QName _EPCISDocument_QNAME = new QName("axis.epcis.oliot.org", "EPCISDocument");
    private final static QName _EventListTypeExtension_QNAME = new QName("", "extension");
    private final static QName _EventListTypeTransactionEvent_QNAME = new QName("", "TransactionEvent");
    private final static QName _EventListTypeObjectEvent_QNAME = new QName("", "ObjectEvent");
    private final static QName _EventListTypeQuantityEvent_QNAME = new QName("", "QuantityEvent");
    private final static QName _EventListTypeAggregationEvent_QNAME = new QName("", "AggregationEvent");
    private final static QName _EventListTypeSensorEvent_QNAME = new QName("", "SensorEvent");
    private final static QName _EventListTypeTransformationEvent_QNAME = new QName("", "TransformationEvent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EPCISDocumentType }
     * 
     */
    public EPCISDocumentType createEPCISDocumentType() {
        return new EPCISDocumentType();
    }

    /**
     * Create an instance of {@link EPCISHeaderExtensionType }
     * 
     */
    public EPCISHeaderExtensionType createEPCISHeaderExtensionType() {
        return new EPCISHeaderExtensionType();
    }

    /**
     * Create an instance of {@link SourceDest }
     * 
     */
    public SourceDest createSourceDestType() {
        return new SourceDest();
    }

    /**
     * Create an instance of {@link BusinessTransaction }
     * 
     */
    public BusinessTransaction createBusinessTransactionType() {
        return new BusinessTransaction();
    }

    /**
     * Create an instance of {@link TransactionEventExtension }
     * 
     */
    public TransactionEventExtension createTransactionEventExtensionType() {
        return new TransactionEventExtension();
    }

    /**
     * Create an instance of {@link EPCISEventListExtensionType }
     * 
     */
    public EPCISEventListExtensionType createEPCISEventListExtensionType() {
        return new EPCISEventListExtensionType();
    }

    /**
     * Create an instance of {@link ObjectEventExtension2 }
     * 
     */
    public ObjectEventExtension2 createObjectEventExtension2Type() {
        return new ObjectEventExtension2();
    }

    /**
     * Create an instance of {@link BusinessLocationExtension }
     * 
     */
    public BusinessLocationExtension createBusinessLocationExtensionType() {
        return new BusinessLocationExtension();
    }

    /**
     * Create an instance of {@link ILMDExtension }
     * 
     */
    public ILMDExtension createILMDExtensionType() {
        return new ILMDExtension();
    }

    /**
     * Create an instance of {@link EPCISEventListExtension2Type }
     * 
     */
    public EPCISEventListExtension2Type createEPCISEventListExtension2Type() {
        return new EPCISEventListExtension2Type();
    }

    /**
     * Create an instance of {@link SensorEvent }
     * 
     */
    public SensorEvent createSensorEventType() {
        return new SensorEvent();
    }

    /**
     * Create an instance of {@link SourceList }
     * 
     */
    public SourceList createSourceListType() {
        return new SourceList();
    }

    /**
     * Create an instance of {@link QuantityEvent }
     * 
     */
    public QuantityEvent createQuantityEventType() {
        return new QuantityEvent();
    }

    /**
     * Create an instance of {@link SensorEventExtension }
     * 
     */
    public SensorEventExtension createSensorEventExtensionType() {
        return new SensorEventExtension();
    }

    /**
     * Create an instance of {@link EPCISDocumentExtensionType }
     * 
     */
    public EPCISDocumentExtensionType createEPCISDocumentExtensionType() {
        return new EPCISDocumentExtensionType();
    }

    /**
     * Create an instance of {@link QuantityEventExtension }
     * 
     */
    public QuantityEventExtension createQuantityEventExtensionType() {
        return new QuantityEventExtension();
    }

    /**
     * Create an instance of {@link SensingList }
     * 
     */
    public SensingList createSensingListType() {
        return new SensingList();
    }

    /**
     * Create an instance of {@link ReadPoint }
     * 
     */
    public ReadPoint createReadPointType() {
        return new ReadPoint();
    }

    /**
     * Create an instance of {@link AggregationEvent }
     * 
     */
    public AggregationEvent createAggregationEventType() {
        return new AggregationEvent();
    }

    /**
     * Create an instance of {@link EPCISHeaderType }
     * 
     */
    public EPCISHeaderType createEPCISHeaderType() {
        return new EPCISHeaderType();
    }

    /**
     * Create an instance of {@link TransformationEvent }
     * 
     */
    public TransformationEvent createTransformationEventType() {
        return new TransformationEvent();
    }

    /**
     * Create an instance of {@link EPCISBodyType }
     * 
     */
    public EPCISBodyType createEPCISBodyType() {
        return new EPCISBodyType();
    }

    /**
     * Create an instance of {@link AggregationEventExtension2 }
     * 
     */
    public AggregationEventExtension2 createAggregationEventExtension2Type() {
        return new AggregationEventExtension2();
    }

    /**
     * Create an instance of {@link EventListType }
     * 
     */
    public EventListType createEventListType() {
        return new EventListType();
    }

    /**
     * Create an instance of {@link ILMD }
     * 
     */
    public ILMD createILMDType() {
        return new ILMD();
    }

    /**
     * Create an instance of {@link EPCList }
     * 
     */
    public EPCList createEPCListType() {
        return new EPCList();
    }

    /**
     * Create an instance of {@link SensingElement }
     * 
     */
    public SensingElement createSensingElementType() {
        return new SensingElement();
    }

    /**
     * Create an instance of {@link DestinationList }
     * 
     */
    public DestinationList createDestinationListType() {
        return new DestinationList();
    }

    /**
     * Create an instance of {@link ObjectEventExtension }
     * 
     */
    public ObjectEventExtension createObjectEventExtensionType() {
        return new ObjectEventExtension();
    }

    /**
     * Create an instance of {@link EPCISBodyExtension }
     * 
     */
    public EPCISBodyExtension createEPCISBodyExtensionType() {
        return new EPCISBodyExtension();
    }

    /**
     * Create an instance of {@link TransactionEvent }
     * 
     */
    public TransactionEvent createTransactionEventType() {
        return new TransactionEvent();
    }

    /**
     * Create an instance of {@link QuantityList }
     * 
     */
    public QuantityList createQuantityListType() {
        return new QuantityList();
    }

    /**
     * Create an instance of {@link EPCISEventExtension }
     * 
     */
    public EPCISEventExtension createEPCISEventExtensionType() {
        return new EPCISEventExtension();
    }

    /**
     * Create an instance of {@link TransactionEventExtension2 }
     * 
     */
    public TransactionEventExtension2 createTransactionEventExtension2Type() {
        return new TransactionEventExtension2();
    }

    /**
     * Create an instance of {@link ReadPointExtension }
     * 
     */
    public ReadPointExtension createReadPointExtensionType() {
        return new ReadPointExtension();
    }

    /**
     * Create an instance of {@link ObjectEvent }
     * 
     */
    public ObjectEvent createObjectEventType() {
        return new ObjectEvent();
    }

    /**
     * Create an instance of {@link QuantityElement }
     * 
     */
    public QuantityElement createQuantityElementType() {
        return new QuantityElement();
    }

    /**
     * Create an instance of {@link TransformationEventExtension }
     * 
     */
    public TransformationEventExtension createTransformationEventExtensionType() {
        return new TransformationEventExtension();
    }

    /**
     * Create an instance of {@link BusinessLocation }
     * 
     */
    public BusinessLocation createBusinessLocationType() {
        return new BusinessLocation();
    }

    /**
     * Create an instance of {@link BusinessTransactionList }
     * 
     */
    public BusinessTransactionList createBusinessTransactionListType() {
        return new BusinessTransactionList();
    }

    /**
     * Create an instance of {@link AggregationEventExtension }
     * 
     */
    public AggregationEventExtension createAggregationEventExtensionType() {
        return new AggregationEventExtension();
    }

    /**
     * Create an instance of {@link EPCN }
     * 
     */
    public EPCN createEPC() {
        return new EPCN();
    }

    /**
     * Create an instance of {@link StandardBusinessDocumentHeader }
     * 
     */
    public StandardBusinessDocumentHeader createStandardBusinessDocumentHeader() {
        return new StandardBusinessDocumentHeader();
    }

    /**
     * Create an instance of {@link CorrelationInformation }
     * 
     */
    public CorrelationInformation createCorrelationInformation() {
        return new CorrelationInformation();
    }

    /**
     * Create an instance of {@link StandardBusinessDocument }
     * 
     */
    public StandardBusinessDocument createStandardBusinessDocument() {
        return new StandardBusinessDocument();
    }

    /**
     * Create an instance of {@link BusinessService }
     * 
     */
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link ManifestItem }
     * 
     */
    public ManifestItem createManifestItem() {
        return new ManifestItem();
    }

    /**
     * Create an instance of {@link ServiceTransaction }
     * 
     */
    public ServiceTransaction createServiceTransaction() {
        return new ServiceTransaction();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link DocumentIdentification }
     * 
     */
    public DocumentIdentification createDocumentIdentification() {
        return new DocumentIdentification();
    }

    /**
     * Create an instance of {@link PartnerIdentification }
     * 
     */
    public PartnerIdentification createPartnerIdentification() {
        return new PartnerIdentification();
    }

    /**
     * Create an instance of {@link Partner }
     * 
     */
    public Partner createPartner() {
        return new Partner();
    }

    /**
     * Create an instance of {@link BusinessScope }
     * 
     */
    public BusinessScope createBusinessScope() {
        return new BusinessScope();
    }

    /**
     * Create an instance of {@link Scope }
     * 
     */
    public Scope createScope() {
        return new Scope();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "ScopeInformation")
    public JAXBElement<Object> createScopeInformation(Object value) {
        return new JAXBElement<Object>(_ScopeInformation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorrelationInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "CorrelationInformation", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<CorrelationInformation> createCorrelationInformation(CorrelationInformation value) {
        return new JAXBElement<CorrelationInformation>(_CorrelationInformation_QNAME, CorrelationInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocumentHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocumentHeader")
    public JAXBElement<StandardBusinessDocumentHeader> createStandardBusinessDocumentHeader(StandardBusinessDocumentHeader value) {
        return new JAXBElement<StandardBusinessDocumentHeader>(_StandardBusinessDocumentHeader_QNAME, StandardBusinessDocumentHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "BusinessService", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<BusinessService> createBusinessService(BusinessService value) {
        return new JAXBElement<BusinessService>(_BusinessService_QNAME, BusinessService.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocument")
    public JAXBElement<StandardBusinessDocument> createStandardBusinessDocument(StandardBusinessDocument value) {
        return new JAXBElement<StandardBusinessDocument>(_StandardBusinessDocument_QNAME, StandardBusinessDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "axis.epcis.oliot.org", name = "EPCISDocument")
    public JAXBElement<EPCISDocumentType> createEPCISDocument(EPCISDocumentType value) {
        return new JAXBElement<EPCISDocumentType>(_EPCISDocument_QNAME, EPCISDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISEventListExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extension", scope = EventListType.class)
    public JAXBElement<EPCISEventListExtensionType> createEventListTypeExtension(EPCISEventListExtensionType value) {
        return new JAXBElement<EPCISEventListExtensionType>(_EventListTypeExtension_QNAME, EPCISEventListExtensionType.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionEvent", scope = EventListType.class)
    public JAXBElement<TransactionEvent> createEventListTypeTransactionEvent(TransactionEvent value) {
        return new JAXBElement<TransactionEvent>(_EventListTypeTransactionEvent_QNAME, TransactionEvent.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ObjectEvent", scope = EventListType.class)
    public JAXBElement<ObjectEvent> createEventListTypeObjectEvent(ObjectEvent value) {
        return new JAXBElement<ObjectEvent>(_EventListTypeObjectEvent_QNAME, ObjectEvent.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantityEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityEvent", scope = EventListType.class)
    public JAXBElement<QuantityEvent> createEventListTypeQuantityEvent(QuantityEvent value) {
        return new JAXBElement<QuantityEvent>(_EventListTypeQuantityEvent_QNAME, QuantityEvent.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregationEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AggregationEvent", scope = EventListType.class)
    public JAXBElement<AggregationEvent> createEventListTypeAggregationEvent(AggregationEvent value) {
        return new JAXBElement<AggregationEvent>(_EventListTypeAggregationEvent_QNAME, AggregationEvent.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SensorEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SensorEvent", scope = EventListType.class)
    public JAXBElement<SensorEvent> createEventListTypeSensorEvent(SensorEvent value) {
        return new JAXBElement<SensorEvent>(_EventListTypeSensorEvent_QNAME, SensorEvent.class, EventListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformationEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransformationEvent", scope = EventListType.class)
    public JAXBElement<TransformationEvent> createEventListTypeTransformationEvent(TransformationEvent value) {
        return new JAXBElement<TransformationEvent>(_EventListTypeTransformationEvent_QNAME, TransformationEvent.class, EventListType.class, value);
    }

}
