//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:39:48 PM KST 
//


package org.oliot.model.oliot;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;


@Entity
public class QuantityList {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	@OneToMany
    protected List<QuantityElement> quantityElement=new ArrayList<QuantityElement>();

    
    public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public List<QuantityElement> getQuantityElement() {
        if (quantityElement == null) {
            quantityElement = new ArrayList<QuantityElement>();
        }
        return this.quantityElement;
    }

	public void setQuantityElement(List<QuantityElement> quantityElement) {
		this.quantityElement = quantityElement;
	}

}
