//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:39:48 PM KST 
//


package org.oliot.model.oliot;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.namespace.QName;


@Entity
public class QuantityEventExtension {

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	
	@OneToMany
	List<MapExt> mapExt=new ArrayList<MapExt>();
	   
	
	
	
	@Transient
    @XmlAnyElement(lax = true)
    protected List<Object> any;
	@Transient
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

   
    public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	

	

    public void setAny(List<Object> any) {
		this.any = any;
	}

	public void setOtherAttributes(Map<QName, String> otherAttributes) {
		this.otherAttributes = otherAttributes;
	}

	/**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

	
	public QuantityEventExtension() {
		super();
	}

	public List<MapExt> getMapExt() {
		return mapExt;
	}

	public void setMapExt(List<MapExt> mapExt) {
		this.mapExt = mapExt;
	}

	public List<Object> getAny() {
		return any;
	}

}
