//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:39:48 PM KST 
//


package org.oliot.model.oliot;

import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;



@Entity
@PrimaryKeyJoinColumn (name="EPCISEvent_id")
public class TransformationEvent{//    extends EPCISEvent{
	
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date eventTime;
    @XmlSchemaType(name = "dateTime")
    protected Date recordTime;
    @XmlElement(required = true)
    protected String eventTimeZoneOffset;

	@OneToOne
	@JoinColumn(name="inputEPCList_id")
	protected EPCList inputEPCList;
	@OneToOne
	@JoinColumn(name="inputQuantityList_id")
    protected QuantityList inputQuantityList;
	@OneToOne
	@JoinColumn(name="outputEPCList_id")
    protected EPCList outputEPCList;
	@OneToOne
	@JoinColumn(name="outputQuantityList_id")
    protected QuantityList outputQuantityList;
	
	
	
    protected String transformationID;
    protected String bizStep;
    protected String disposition;
    @OneToOne
	@JoinColumn(name="readPoint_id")
    protected ReadPoint readPoint;
    @OneToOne
	@JoinColumn(name="bizLocation_id")
    protected BusinessLocation bizLocation;
    @OneToOne
	@JoinColumn(name="bizTransactionList_id")
    protected BusinessTransactionList bizTransactionList;
    
    @OneToOne
	@JoinColumn(name="sourceList_id")
    protected SourceList sourceList;
    @OneToOne
	@JoinColumn(name="destinationList_id")
    protected DestinationList destinationList;
    @OneToOne
	@JoinColumn(name="ilmd_id")
    protected ILMD ilmd;
    
    @OneToOne
	@JoinColumn(name="TransformationEventExtension_id")
    protected TransformationEventExtension extension;
    
    @Transient 
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    
	
    
    
    
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Date getEventTime() {
		return eventTime;
	}
	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}
	public Date getRecordTime() {
		return recordTime;
	}
	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}
	public String getEventTimeZoneOffset() {
		return eventTimeZoneOffset;
	}
	public void setEventTimeZoneOffset(String eventTimeZoneOffset) {
		this.eventTimeZoneOffset = eventTimeZoneOffset;
	}
	public QuantityList getInputQuantityList() {
		return inputQuantityList;
	}
	public void setInputQuantityList(QuantityList inputQuantityList) {
		this.inputQuantityList = inputQuantityList;
	}
	public EPCList getOutputEPCList() {
		return outputEPCList;
	}
	public void setOutputEPCList(EPCList outputEPCList) {
		this.outputEPCList = outputEPCList;
	}
	public QuantityList getOutputQuantityList() {
		return outputQuantityList;
	}
	public void setOutputQuantityList(QuantityList outputQuantityList) {
		this.outputQuantityList = outputQuantityList;
	}
	public String getTransformationID() {
		return transformationID;
	}
	public void setTransformationID(String transformationID) {
		this.transformationID = transformationID;
	}
	public String getBizStep() {
		return bizStep;
	}
	public void setBizStep(String bizStep) {
		this.bizStep = bizStep;
	}
	public String getDisposition() {
		return disposition;
	}
	public void setDisposition(String disposition) {
		this.disposition = disposition;
	}
	public ReadPoint getReadPoint() {
		return readPoint;
	}
	public void setReadPoint(ReadPoint readPoint) {
		this.readPoint = readPoint;
	}
	public BusinessLocation getBizLocation() {
		return bizLocation;
	}
	public void setBizLocation(BusinessLocation bizLocation) {
		this.bizLocation = bizLocation;
	}
	public BusinessTransactionList getBizTransactionList() {
		return bizTransactionList;
	}
	public void setBizTransactionList(BusinessTransactionList bizTransactionList) {
		this.bizTransactionList = bizTransactionList;
	}
	public SourceList getSourceList() {
		return sourceList;
	}
	public void setSourceList(SourceList sourceList) {
		this.sourceList = sourceList;
	}
	public DestinationList getDestinationList() {
		return destinationList;
	}
	public void setDestinationList(DestinationList destinationList) {
		this.destinationList = destinationList;
	}
	public ILMD getIlmd() {
		return ilmd;
	}
	public void setIlmd(ILMD ilmd) {
		this.ilmd = ilmd;
	}
	public TransformationEventExtension getExtension() {
		return extension;
	}
	public void setExtension(TransformationEventExtension extension) {
		this.extension = extension;
	}
	public List<Object> getAny() {
		return any;
	}
	public void setAny(List<Object> any) {
		this.any = any;
	}
	public EPCList getInputEPCList() {
		return inputEPCList;
	}
	public void setInputEPCList(EPCList inputEPCList) {
		this.inputEPCList = inputEPCList;
	}

    
   

}
